<?php


namespace Imee\Controller\Audit;

use Imee\Controller\BaseController;
use Imee\Service\Domain\Service\Audit\CircleReportService;

/**
 * 朋友圈举报
 * Class CirclereportController
 * @package Imee\Controller\Audit
 */
class CirclereportController extends BaseController
{
    public $params;

    public function onConstruct()
    {
        parent::onConstruct(); // TODO: Change the autogenerated stub
        $get = $this->request->getQuery();
        $post = $this->request->getPost();
        $this->params = array_merge(
            ['admin' => $this->uid],
            $get,
            $post
        );
    }


    /**
     * @page circlereport
     * @name 审核系统-举报管理-动态举报
     * @point 列表
     */
    public function indexAction()
    {
        $service = new CircleReportService();
        $res = $service->getCheckedList($this->params);
        return $this->outputSuccess($res['data'], ['total' => $res['total']]);
    }

    /**
     * @page circlereport
     * @point 审核
     */
    public function verifyAction()
    {
        $service = new CircleReportService();
        $res = $service->multpass($this->params);
        return $this->outputSuccess($res);
    }

    /**
     * @page circlereport
     * @point 审核日志
     */
    public function historyAction()
    {
        $service = new CircleReportService();
        $res = $service->history($this->params);
        return $this->outputSuccess($res['data'], ['total' => $res['total']]);
    }


    /**
     * @page circlereport
     * @point 举报记录
     */
    public function rhistoryAction()
    {
        $service = new CircleReportService();
        $res = $service->rhistory($this->params);
        return $this->outputSuccess($res['data'], ['total' => $res['total']]);
    }


    /**
     * @page circlereport
     * @point 配置
     */
    public function configAction()
    {
        $service = new CircleReportService();
        $res = $service->getConfig();
        return $this->outputSuccess($res);
    }
}
