<?php


namespace Imee\Controller\Audit;


use Imee\Controller\BaseController;
use Imee\Service\Domain\Service\Csms\CsmsToolService;

class CsmstoolController extends BaseController
{


    public $params;

    public function onConstruct()
    {
        parent::onConstruct(); // TODO: Change the autogenerated stub
        $get = $this->request->getQuery();
        $post = $this->request->getPost();
        $this->params = array_merge(
            ['admin' => $this->uid],
            $get,
            $post
        );

        $handle = $this->params['handle'] ?? '';
        if($handle == 'list'){
            $this->params['sort'] = 'id';
        }
    }


    /**
     * @page csmstasklist
     * @name 审核系统-内容安全-任务日志
     * @point 内容安全任务日志
     */
    public function tasklistAction()
    {
        $handle = $this->params['handle'] ?? 'list';
        $service = new CsmsToolService();
        if($handle == 'config'){
            $res = $service->taskConfig($this->params);
            return $this->outputSuccess($res);
        }
        if($handle == 'list'){
            $res = $service->taskList($this->params);
            return $this->outputSuccess($res['data'], ['total' => $res['total']]);
        }
        if($handle == 'retry'){
            $res = $service->taskRetry($this->params);
            return $this->outputSuccess($res);
        }

        return $this->outputSuccess();
    }


    /**
     * @page csmschange
     * @name 审核系统-内容安全-任务变更日志
     * @point 内容安全任务变更日志
     */
    public function changelistAction()
    {
        $handle = $this->params['handle'] ?? 'list';
        $service = new CsmsToolService();
        if($handle == 'config'){
            $res = $service->changeConfig($this->params);
            return $this->outputSuccess($res);
        }
        if($handle == 'list'){
            $res = $service->changeList($this->params);
            return $this->outputSuccess($res['data'], ['total' => $res['total']]);
        }
        return $this->outputSuccess();
    }



    /**
     * @page csmsreviewlist
     * @name 审核系统-内容安全-外显日志
     * @point 内容安全外显日志
     */
    public function reviewlistAction()
    {
        $handle = $this->params['handle'] ?? 'list';
        $service = new CsmsToolService();
        if($handle == 'config'){
            $res = $service->reviewConfig($this->params);
            return $this->outputSuccess($res);
        }
        if($handle == 'list'){
            $res = $service->reviewList($this->params);
            return $this->outputSuccess($res['data'], ['total' => $res['total']]);
        }
        if($handle == 'retry'){
            $res = $service->reviewRetry($this->params);
            return $this->outputSuccess($res);
        }
        return $this->outputSuccess();
    }

    /**
     * @page csmsimagelist
     * @name 审核系统-内容安全-图片检测日志
     * @point 图片检测日志
     */
    public function imagelistAction()
    {
        $handle = $this->params['handle'] ?? 'list';
        $service = new CsmsToolService();
        if($handle == 'config'){
            $res = $service->imageConfig($this->params);
            return $this->outputSuccess($res);
        }
        if($handle == 'list'){
            $res = $service->imageList($this->params);
            return $this->outputSuccess($res['data'], ['total' => $res['total']]);
        }
        return $this->outputSuccess();
    }


    /**
     * @page csmsspamlist
     * @name 审核系统-内容安全-spam检测日志
     * @point spam检测日志
     */
    public function spamlistAction()
    {
        $handle = $this->params['handle'] ?? 'list';
        $service = new CsmsToolService();
        if($handle == 'config'){
            $res = $service->spamConfig($this->params);
            return $this->outputSuccess($res);
        }
        if($handle == 'list'){
            $res = $service->spamList($this->params);
            return $this->outputSuccess($res['data'], ['total' => $res['total']]);
        }
        return $this->outputSuccess();
    }


    /**
     * @page csmsaudiolist
     * @name 审核系统-内容安全-音频检测日志
     * @point 音频检测日志
     */
    public function audiolistAction()
    {
        $handle = $this->params['handle'] ?? 'list';
        $service = new CsmsToolService();
        if($handle == 'config'){
            $res = $service->audioConfig($this->params);
            return $this->outputSuccess($res);
        }
        if($handle == 'list'){
            $res = $service->audioList($this->params);
            return $this->outputSuccess($res['data'], ['total' => $res['total']]);
        }
        return $this->outputSuccess();
    }


    /**
     * @page csmspushtest
     * @name 审核系统-内容安全-推送测试
     * @point 内容推送测试
     */
    public function pushtestAction()
    {
        $handle = $this->params['handle'] ?? 'list';
        $service = new CsmsToolService();
        if($handle == 'config'){
            $res = $service->pushConfig($this->params);
            return $this->outputSuccess($res);
        }
        if($handle == 'push'){
            $res = $service->pushTest($this->params);
            return $this->outputSuccess($res);
        }
        return $this->outputSuccess();
    }

}