<?php


namespace Imee\Controller\Audit;


use Imee\Controller\BaseController;
use Imee\Service\Domain\Service\Audit\DirtySumService;


/**
 * 敏感词触发数据统计
 * Class DirtysumController
 * @package Imee\Controller\Audit
 */


class DirtysumController extends BaseController
{

    public $params;

    public function onConstruct()
    {
        parent::onConstruct(); // TODO: Change the autogenerated stub
        $get = $this->request->getQuery();
        $post = $this->request->getPost();
        $this->params = array_merge(
            ['admin' => $this->uid],
            $get,
            $post
        );
    }

    /**
     * @page dirtysum
     * @name 审核系统-敏感词管理-敏感词触发数据
     * @point 列表
     */
    public function indexAction()
    {
        $service = new DirtySumService();
        $res = $service->list($this->params);
        return $this->outputSuccess($res['data'], ['total' => $res['total']]);
    }

    /**
     * @page dirtysum
     * @point 配置
     */
    public function configAction()
    {

    }

}