<?php


namespace Imee\Controller\Audit;

use Imee\Controller\BaseController;
use Imee\Controller\Validation\Audit\Dirtytrigger\DirtyTriggerListValidation;
use Imee\Controller\Validation\Audit\Dirtytrigger\DirtyTriggerLogValidation;
use Imee\Controller\Validation\Audit\Dirtytrigger\DirtyTriggerModifyValidation;
use Imee\Service\Domain\Context\Audit\Dirtytrigger\DirtyTriggerListContext;
use Imee\Service\Domain\Context\Audit\Dirtytrigger\DirtyTriggerLogContext;
use Imee\Service\Domain\Context\Audit\Dirtytrigger\DirtyTriggerModifyContext;
use Imee\Service\Domain\Service\Audit\DirtyTriggerService;

/**
 * 敏感词触发审核
 * Class DirtytriggerController
 * @package Imee\Controller\Audit
 */
class DirtytriggerController extends BaseController
{
    public $params;

    public function onConstruct()
    {
        parent::onConstruct(); // TODO: Change the autogenerated stub
        $get = $this->request->getQuery();
        $post = $this->request->getPost();
        $this->params = array_merge(
            ['admin' => $this->uid],
            $get,
            $post
        );
    }


    /**
     * @page dirtytrigger
     * @name 审核系统-敏感词管理-敏感词触发
     * @point 敏感词触发列表
     */
    public function listAction()
    {
        DirtyTriggerListValidation::make()->validators($this->params);
        $context = new DirtyTriggerListContext($this->params);
        $service = new DirtyTriggerService();
        $res = $service->list($context);
        return $this->outputSuccess($res['data'], ['total' => $res['total']]);
    }


    /**
     * @page dirtytrigger
     * @point 配置
     */
    public function configAction()
    {
        $service  = new DirtyTriggerService();
        $res = $service->config();
        return $this->outputSuccess($res);
    }




}
