<?php

namespace Imee\Controller\Audit;

use Imee\Controller\BaseController;
use Imee\Service\Domain\Service\Audit\Report\ChatService;
use Imee\Service\Domain\Service\Audit\Report\UserReportService;
use Imee\Service\Domain\Service\Audit\Report\Validation\ChatValidation;
use Imee\Service\Domain\Service\Audit\Report\Validation\CheckUserValidation;
use Imee\Service\Domain\Service\Audit\Report\Validation\UserReportInfoValidation;
use Imee\Service\Domain\Service\Audit\Report\Validation\UserReportValidation;

class ReportController extends BaseController
{
    public $params;

    public function onConstruct()
    {
        parent::onConstruct(); // TODO: Change the autogenerated stub
        $get = $this->request->getQuery();
        $post = $this->request->getPost();
        $this->params = array_merge(
            ['admin' => $this->uid],
            $get,
            $post
        );
    }

    /**
     * @page userReportManager
     * @name 举报管理 - 用户举报列表
     * @point 用户举报列表
     * @return \Phalcon\Http\ResponseInterface
     * @throws \Imee\Exception\CommonException
     */
    public function userReportAction()
    {
        UserReportValidation::make()->validators($this->params);
        $service = UserReportService::getInstance();
        $result = $service->setContext($this->params)->userReportList();
        return $this->outputSuccess($result);
    }

    /**
     * @page userReportManager
     * @point 用户举报审核
     * @return \Phalcon\Http\ResponseInterface
     * @throws \Imee\Exception\CommonException
     */
    public function checkUserReportAction()
    {
        CheckUserValidation::make()->validators($this->params);
        $service = UserReportService::getInstance();
        $service->setContext($this->params)->checkUserReport();
        return $this->outputSuccess();
    }

    /**
     * @page userReportManager
     * @point 用户举报下拉配置
     * @return \Phalcon\Http\ResponseInterface
     */
    public function reportConfigAction()
    {
        $service = UserReportService::getInstance();
        $result = $service->reportConfig();
        return $this->outputSuccess($result);
    }

    /**
     * @page userReportManager
     * @point 聊天历史
     * @return \Phalcon\Http\ResponseInterface
     * @throws \Imee\Exception\CommonException
     */
    public function chatHistoryAction()
    {
        ChatValidation::make()->validators($this->params);
        $service = ChatService::getInstance();
        $result = $service->setContext($this->params)->chatList();
        return $this->outputSuccess($result);
    }

    /**
     * @page roomReportManager
     * @name 举报管理 - 房间举报列表
     * @point 房间举报列表
     */
    public function roomReportAction()
    {
        UserReportValidation::make()->validators($this->params);
        $service = UserReportService::getInstance();
        $result = $service->setContext($this->params)->roomReportList();
        return $this->outputSuccess($result);
    }

    /**
     * @page roomReportManager
     * @point 房间审核记录
     * @return \Phalcon\Http\ResponseInterface
     * @throws \Imee\Exception\CommonException
     */
    public function operateListAction()
    {
        UserReportValidation::make()->validators($this->params);
        $service = UserReportService::getInstance();
        $result = $service->setContext($this->params)->operateList();
        return $this->outputSuccess($result);
    }



}