<?php

namespace Imee\Controller\Operate;

use Imee\Controller\BaseController;
use Imee\Service\Operate\Roombackground\BackgroundService;

class BackgroundlogController extends BaseController
{
    /**
     * @var BackgroundService $service
     */
    private $service;

    protected function onConstruct()
    {
        parent::onConstruct(); // TODO: Change the autogenerated stub
        $this->service = new BackgroundService();
    }

    /**
     * @page backgroundlog
     * @name 运营系统-房间背景管理-背景日志
     */
    public function mainAction()
    {
    }

    /**
     * @page backgroundlog
     * @point 列表
     */
    public function listAction()
    {
        $list = $this->service->getLogList($this->params);
        return $this->outputSuccess($list['data'], ['total' => $list['total']]);
    }
}