<?php

namespace Imee\Controller\Operate;

use Imee\Controller\BaseController;
use Imee\Controller\Validation\Roombackground\BackgroundKnapsackEditValidation;
use Imee\Service\Operate\Roombackground\BackgroundKnapsackService;

class BackgroundknapsackController extends BaseController
{
    /**
     * @var BackgroundKnapsackService $service
     */
    private $service;

    protected function onConstruct()
    {
        parent::onConstruct(); // TODO: Change the autogenerated stub
        $this->service = new BackgroundKnapsackService();
    }

    /**
     * @page backgroundknapsack
     * @name 运营系统-房间背景管理-背景背包管理
     */
    public function mainAction()
    {
    }

    /**
     * @page backgroundknapsack
     * @point 列表
     */
    public function listAction()
    {
        $list = $this->service->getList($this->params);
        return $this->outputSuccess($list['data'], ['total' => $list['total']]);
    }

    /**
     * @page backgroundknapsack
     * @point 修改
     */
    public function modifyAction()
    {
        BackgroundKnapsackEditValidation::make()->validators($this->params);
        list($res, $msg) = $this->service->modify($this->params);
        if (!$res) {
            return $this->outputError(-1, $msg);
        }
        return $this->outputSuccess($msg);
    }

    /**
     * @page reebackground
     * @point 删除
     */
    public function deleteAction()
    {
        if (!isset($this->params['bg_id']) || empty($this->params['bg_id'])) {
            return $this->outputError(-1, 'Background ID错误');
        }
        list($res, $msg) = $this->service->delete($this->params['bg_id']);
        if (!$res) {
            return $this->outputError(-1, $msg);
        }
        return $this->outputSuccess($msg);
    }
}