<?php

namespace Imee\Controller\Operate;

use Imee\Controller\BaseController;
use Imee\Controller\Validation\Roombackground\BackgroundGoodsCreateValidation;
use Imee\Controller\Validation\Roombackground\BackgroundGoodsModifyValidation;
use Imee\Service\Operate\Roombackground\BackgroundGoodsService;

class CustombackgroundController extends BaseController
{
    /**
     * @var BackgroundGoodsService $service
     */
    private $service;

    protected function onConstruct()
    {
        parent::onConstruct(); // TODO: Change the autogenerated stub
        $this->service = new BackgroundGoodsService();
    }

    /**
     * @page custombackground
     * @name 自定义背景管理
     */
    public function mainAction()
    {
    }

    /**
     * @page custombackground
     * @point 列表
     */
    public function listAction()
    {
        $this->params['is_free'] = 1;
        $this->params['source'] = 1;
        $list = $this->service->getList($this->params);
        return $this->outputSuccess($list['data'], ['total' => $list['total']]);
    }

    /**
     * @page custombackground
     * @point 创建
     */
    public function createAction()
    {
        $c = $this->params['c'] ?? '';
        if ($c == 'enum') {
            return $this->outputSuccess($this->service->getMaterialMap($this->params['str']));
        }
        BackgroundGoodsCreateValidation::make()->validators($this->params);
        list($res, $msg) = $this->service->create($this->params);
        if (!$res) {
            return $this->outputError(-1, $msg);
        }
        return $this->outputSuccess($msg);
    }

    /**
     * @page custombackground
     * @point 修改
     */
    public function modifyAction()
    {
        BackgroundGoodsModifyValidation::make()->validators($this->params);
        list($res, $msg) = $this->service->modify($this->params);
        if (!$res) {
            return $this->outputError(-1, $msg);
        }
        return $this->outputSuccess($msg);
    }

    /**
     * @page custombackground
     * @point 删除
     */
    public function deleteAction()
    {
        if (!isset($this->params['bg_id']) || empty($this->params['bg_id'])) {
            return $this->outputError(-1, 'Background ID错误');
        }
        list($res, $msg) = $this->service->delete($this->params['bg_id']);
        if (!$res) {
            return $this->outputError(-1, $msg);
        }
        return $this->outputSuccess($msg);
    }
}