<?php

namespace Imee\Controller\Operate;

use Imee\Controller\BaseController;
use Imee\Controller\Validation\Roombackground\BackgroundCreateValidation;
use Imee\Controller\Validation\Roombackground\BackgroundGoodsCreateValidation;
use Imee\Controller\Validation\Roombackground\BackgroundGoodsModifyValidation;
use Imee\Controller\Validation\Roombackground\BackgroundModifyValidation;
use Imee\Service\Operate\Roombackground\BackgroundGoodsService;
use Imee\Service\Operate\Roombackground\BackgroundService;

class FreebackgroundController extends BaseController
{
    /**
     * @var BackgroundGoodsService $service
     */
    private $service;

    protected function onConstruct()
    {
        parent::onConstruct(); // TODO: Change the autogenerated stub
        $this->service = new BackgroundGoodsService();
    }

    /**
     * @page freebackground
     * @name 免费背景商品
     */
    public function mainAction()
    {
    }

    /**
     * @page reebackground
     * @point 列表
     */
    public function listAction()
    {
        $this->params['is_free'] = 1;
        $this->params['source'] = 0;
        $list = $this->service->getList($this->params);
        return $this->outputSuccess($list['data'], ['total' => $list['total']]);
    }

    /**
     * @page reebackground
     * @point 创建
     */
    public function createAction()
    {
        BackgroundGoodsCreateValidation::make()->validators($this->params);
        list($res, $msg) = $this->service->create($this->params);
        if (!$res) {
            return $this->outputError(-1, $msg);
        }
        return $this->outputSuccess($msg);
    }

    /**
     * @page reebackground
     * @point 修改
     */
    public function modifyAction()
    {
        BackgroundGoodsModifyValidation::make()->validators($this->params);
        list($res, $msg) = $this->service->modify($this->params);
        if (!$res) {
            return $this->outputError(-1, $msg);
        }
        return $this->outputSuccess($msg);
    }

    /**
     * @page reebackground
     * @point 删除
     */
    public function deleteAction()
    {
        if (!isset($this->params['bg_id']) || empty($this->params['bg_id'])) {
            return $this->outputError(-1, 'Background ID错误');
        }
        list($res, $msg) = $this->service->delete($this->params['bg_id']);
        if (!$res) {
            return $this->outputError(-1, $msg);
        }
        return $this->outputSuccess($msg);
    }
}