<?php

namespace Imee\Controller\Operate;

use Imee\Controller\BaseController;
use Imee\Controller\Validation\Luckywheel\TicketsPriceValidation;
use Imee\Models\Xs\XsLuckyWheelConfig;
use Imee\Service\Luckywheel\LuckyWheelConfigService;

class LuckywheelticketsController extends BaseController
{
    /**
     * @var LuckyWheelConfigService $service
     */
    private $service;

    protected function onConstruct()
    {
        parent::onConstruct(); // TODO: Change the autogenerated stub
        $this->service = new LuckyWheelConfigService(XsLuckyWheelConfig::TICKETS_PRICE_FIELD);
    }

    /**
     * @page luckywheeltickets
     * @name 运营系统-玩法管理-LuckyWheel玩法-入场费配置
     */
    public function mainAction()
    {
    }

    /**
     * @page luckywheeltickets
     * @point 列表
     */
    public function listAction()
    {
        $res = $this->service->getList();
        return $this->outputSuccess([$res]);
    }

    /**
     * @page  luckywheeltickets
     * @point 修改
     */
    public function modifyAction()
    {
        TicketsPriceValidation::make()->validators($this->params);
        [$result, $msg] = $this->service->modify($this->params);
        if (!$result) {
            return $this->outputError('-1', $msg);
        }
        return $this->outputSuccess($result);
    }
}