<?php

namespace Imee\Controller\Operate;

use Imee\Controller\BaseController;
use Imee\Controller\Validation\Luckywheel\JoinNumsValidation;
use Imee\Service\Luckywheel\RegionSwitchService;

class LuckywheelregionController extends BaseController
{
	protected function onConstruct()
	{
		parent::onConstruct(); // TODO: Change the autogenerated stub
		$this->service = new RegionSwitchService();
	}

	/**
	 * @page luckywheelregion
	 * @name 运营系统-玩法管理-LuckyWheel玩法-大区开关
	 */
	public function mainAction()
	{
	}

	/**
	 * @page luckywheelregion
	 * @point 列表
	 */
	public function listAction()
	{
		$res = $this->service->getList($this->params, 'id desc', 1, 20);
		return $this->outputSuccess($res['data'] ?? [], ['total' => $res['total'] ?? 0]);
	}

	/**
	 * @page  luckywheelregion
	 * @point 修改
	 */
	public function modifyAction()
	{
		[$result, $msg] = $this->service->modify($this->params['bigarea_id'], $this->params['switch']);
		if (!$result) {
			return $this->outputError('-1', $msg);
		}
		return $this->outputSuccess($result);
	}
}