<?php

namespace Imee\Controller\Operate;

use Imee\Controller\BaseController;
use Imee\Service\Luckygift\AnchorDivideService;

class LuckygiftanchordivideController extends BaseController
{
	/** @var  AnchorDivideService $service */
	private $service;

	protected function onConstruct()
	{
		parent::onConstruct(); // TODO: Change the autogenerated stub
		$this->service = new AnchorDivideService();
	}

	/**
	 * @page luckygiftanchordivide
	 * @name 幸运礼物玩法配置-幸运礼物直播分成
	 */
	public function mainAction()
	{
	}

	/**
	 * @page luckygiftanchordivide
	 * @point 列表
	 */
	public function listAction()
	{
		$res = $this->service->getList($this->params, $this->params['page'], $this->params['limit']);
		return $this->outputSuccess($res['data'], ['total' => $res['total']]);
	}

	/**
	 * @page  luckygiftanchordivide
	 * @point 新增
	 */
	public function createAction()
	{
		if (!isset($this->params['proportion']) || !in_array($this->params['proportion'],[0, 20])) {
			return $this->outputError('-1','比例必选');
		}

		if (empty($this->params['gift_id_name'])) {
			return $this->outputError('-1', '礼物必选');
		}

		[$result, $msg] = $this->service->add($this->params['proportion'], $this->params['gift_id_name']);
		if (!$result) {
			return $this->outputError('-1', $msg);
		}
		return $this->outputSuccess($result);
	}

	/**
	 * @page  luckygiftanchordivide
	 * @point 修改
	 */
	public function modifyAction()
	{
		if (empty($this->params['id'])) {
			return $this->outputError('-1','id必传');
		}

		if (!isset($this->params['proportion']) || !in_array($this->params['proportion'],[0, 20])) {
			return $this->outputError('-1','比例必选');
		}

		if (empty($this->params['gift_id_name'])) {
			return $this->outputError('-1', '礼物必选');
		}

		[$result, $msg] = $this->service->edit($this->params['id'], $this->params['proportion'], $this->params['gift_id_name']);
		if (!$result) {
			return $this->outputError('-1', $msg);
		}
		return $this->outputSuccess($result);
	}

	/**
	 * @page  luckygiftanchordivide
	 * @point 删除
	 */
	public function deleteAction()
	{
		if (empty($this->params['id'])) {
			return $this->outputError('-1', 'id必须');
		}

		[$result, $msg] = $this->service->delete($this->params['id']);
		if (!$result) {
			return $this->outputError('-1', $msg);
		}
		return $this->outputSuccess($result);
	}
}