<?php

namespace Imee\Controller\Operate;

use Imee\Controller\BaseController;
use Imee\Controller\Validation\Luckywheel\JoinNumsValidation;
use Imee\Models\Xs\XsLuckyWheelConfig;
use Imee\Service\Luckywheel\LuckyWheelConfigService;

class LuckywheeljoinnumsController extends BaseController
{
    /**
     * @var LuckyWheelConfigService $service
     */
    private $service;

    protected function onConstruct()
    {
        parent::onConstruct(); // TODO: Change the autogenerated stub
        $this->service = new LuckyWheelConfigService(XsLuckyWheelConfig::JOIN_NUMS_FIELD);
    }

    /**
     * @page luckywheeljoinnums
     * @name 运营系统-玩法管理-LuckyWheel玩法-参与人数上限配置
     */
    public function mainAction()
    {
    }

    /**
     * @page luckywheeljoinnums
     * @point 列表
     */
    public function listAction()
    {
        $res = $this->service->getList();
        return $this->outputSuccess([$res]);
    }

    /**
     * @page  luckywheeljoinnums
     * @point 修改
     */
    public function modifyAction()
    {
        JoinNumsValidation::make()->validators($this->params);
        [$result, $msg] = $this->service->modify($this->params);
        if (!$result) {
            return $this->outputError('-1', $msg);
        }
        return $this->outputSuccess($result);
    }
}