<?php
namespace Imee\Models\Es;

class EsXsUserProfile  extends ESBase
{

    public $primaryKey = 'id';

    public function getIndexName()
    {
        return ENV == 'dev' ? 'xianshi.xs_user_profile' : 'xianshi.xs_user_profile_v5';
    }

    public function getTypeName()
    {
        return ENV == 'dev' ? '_doc' : 'default';
    }

    public $mappingProperties = [
        'app_id'          => ['type' => 'byte'],
        'channel'         => ['type' => 'text'],
        'dateline'        => ['type' => 'long'],
        'deleted'         => ['type' => 'byte'],
        'name'            => ['type' => 'text'],
        'online_dateline' => ['type' => 'long'],
        'online_status'   => ['type' => 'byte'],
        'pay_money'       => ['type' => 'long'],
        'pay_room_money'  => ['type' => 'long'],
        'role'            => ['type' => 'byte'],
        'sex'             => ['type' => 'byte'],
        'sign'            => ['type' => 'text'],
        'uid'             => ['type' => 'long'],
        'language'        => ['type' => 'text'],
        'level'           => ['type' => 'byte'],
        'bigarea_id'      => ['type' => 'short'],
        'platform'        => ['type' => 'byte'],
        'version'         => ['type' => 'text',"fields" => ['keyword' => ['type'=>'keyword', 'ignore_above' => 256]]],
    ];

    public function getKeyName()
    {
        return parent::getKeyName(); // TODO: Change the autogenerated stub
    }
}