<?php


namespace Imee\Controller\Operate\Func;

use Imee\Controller\BaseController;
use Imee\Controller\Validation\Operate\Func\QuickGiftConfigModifyValidation;
use Imee\Models\Xs\XsQuickGiftConfig;
use Imee\Service\Operate\Func\QuickGiftConfigService;

class VideoquickgiftController extends BaseController
{
    /**
     * @var QuickGiftConfigService $service
     */
    private $service;

    protected function onConstruct()
    {
        parent::onConstruct(); // TODO: Change the autogenerated stub
        $this->service = new QuickGiftConfigService();
    }

    /**
     * @page videoquickgift
     * @name 视频房快捷礼物配置
     */
    public function mainAction()
    {
    }

    /**
     * @page videoquickgift
     * @point list
     */
    public function listAction()
    {
        $list = $this->service->getList($this->params, XsQuickGiftConfig::ROOM_TYPE_VIDEO);

        return $this->outputSuccess($list['data'], ['total' => $list['total']]);
    }

    /**
     * @page videoquickgift
     * @point modify
     * @logRecord(content = '修改', action = '1', model = 'videoquickgift', model_id = 'bigarea_id')
     */
    public function modifyAction()
    {
        QuickGiftConfigModifyValidation::make()->validators($this->params);
        list($res, $data) = $this->service->modify($this->params, XsQuickGiftConfig::ROOM_TYPE_VIDEO);

        if (!$res) {
            return $this->outputError(-1, $data);
        }

        return $this->outputSuccess($data);
    }
}