<?php


namespace Imee\Controller\Open;


use Imee\Controller\BaseOpenController;
use Imee\Helper\Constant\CsmsConstant;
use Imee\Service\Domain\Service\Csms\Task\CsmsReviewService;
use Imee\Service\Domain\Service\Csms\Task\CsmsSecondVerifyService;

class CsmsController extends BaseOpenController
{

    public $params;

    public function onConstruct()
    {
        parent::onConstruct(); // TODO: Change the autogenerated stub
        $get = $this->request->getQuery();
        $post = $this->request->getPost();
        $put = $this->request->getPut();
        $this->params = array_merge(
            $get,
            $post,
            $put
        );
    }


    /**
     * api review
     * @return mixed
     */
    public function reviewAction()
    {
        $stage = $this->params['stage'] ?? '';              // 审核阶段
        $data = $this->params['data'] ?? [];                // 外显数据
        $config = $this->params['config'] ?? [];            // 外显配置
        $res = [];
        if($stage == CsmsConstant::CSMS_AUDIT){
            $reviewService = new CsmsReviewService();
            $res = $reviewService->handle($data, $stage, $config);
        }
        if($stage == CsmsConstant::CSMS_RECHECK){
            $reviewService = new CsmsSecondVerifyService();
            $res = $reviewService->handle($data, $stage, $config);
        }
        return $this->outputJson($res);
    }

}