<?php

namespace Imee\Controller\Open;

use Imee\Comp\Common\Redis\RedisBase;
use Imee\Controller\BaseOpenController;
use Imee\Exception\ApiException;
use Imee\Service\Operate\WelcomegiftbagService;

class OperateController extends BaseOpenController
{
    const SALT = 'RvGzP9Hh8tHOpWdj';

    public $params;

    public function onConstruct()
    {
        parent::onConstruct(); // TODO: Change the autogenerated stub
        $get = $this->request->getQuery();
        $post = $this->request->getPost();
        $put = $this->request->getPut();
        $this->params = array_merge(
            $get,
            $post,
            $put
        );
    }

    /**
     * 迎新礼包下发
     * @return mixed
     */
    public function sendWelcomeGiftBagAction()
    {
        $salt = $this->params['salt'] ?? '';
        $uid = $this->params['uid'] ?? 0;
        $bid = $this->params['bid'] ?? 0;
        $gbId = $this->params['gb_id'] ?? 0;
        $num =$this->params['num'] ?? 0;
        $validDay = $this->params['valid_day'] ?? 0;
        $bigAreaId = $this->params['big_area_id'] ?? 0;
        $operateUid = $this->params['operate_uid'] ?? 0;

        if (empty($salt) || empty($uid) || empty($gbId) || empty($num) || empty($validDay) || empty($bigAreaId) || empty($operateUid)) {
            return $this->outputError(-1,'参数错误');
        }

        if ($salt != self::SALT) {
            return $this->outputError(-1,'访问无效');
        }
        $redis = new RedisBase(RedisBase::REDIS_ADMIN);
        $key = md5("gb_send_{$uid}_{$gbId}_{$bigAreaId}_{$num}_{$validDay}");
        if (!$redis->setNX($key, 1)) {
            return $this->outputError(-1,'5秒内，不可重复配置');
        }
        $redis->expire($key, 10);
        try {
            WelcomegiftbagService::getInstance()->createBroker($this->params);
        } catch (ApiException $exception) {
            return $this->outputError(-1, $exception->getMsg());
        }
        return $this->outputSuccess([]);
    }


}