<?php
$__messages = array(
	"房间违规" => "A sala violou regras.",
    "发布第三方广告" => "Publicar propagandas de terceiros.",
    "越过平台走现金单" => "Ignorar a plataforma e tratar pedidos em dinheiro.",
    "发布色情信息" => "Publicar informações pornográficas.",
    "发布诈骗信息" => "Publicar informações fraudulentas.",
    "订单涉黄" => "O pedido envolve pornografia.",
    "发布毒品/博彩/投注等违法信息" => "Publicar informações ilegais como drogas/jogos/apostas.",
    "发布违法信息" => "Publicar informações ilegais.",
    "发布反动信息" => "liberar informações reacionárias.",
    "一人创建多个技能认证账号" => "Criar várias contas verificadas de habilidade por uma pessoa.",
    "非本人服务" => "Serviços não prestados por você próprio.",
    "不按资质和订单规定内容服务" => "Não oferecer serviços de acordo com qualificações e ordens específicos.",
    "资质与本人不符" => "A qualificação não corresponde à sua situação",
    "服务态度恶劣" => "Atitude de serviço ruim",
    "强制用户下多倍单" => "Forçar os usuários a fazer vários pedidos",
    "未提供订单服务" => "Não oferecer serviços nos pedidos",
    "在聊天室进行低俗/色情表演" => "Realizar performances vulgares/pornográficas em salas de bate-papo",
    "在聊天室播放低俗/色情歌曲或配音" => "Tocar músicas ou dublagens vulgares/pornográficas em salas de bate-papo",
    "在聊天室说低俗/色情擦边词语" => "Falar palavras limítrofes vulgares/pornográficas em salas de bate-papo",
    "在聊天室收到打赏不提供服务" => "Não prestar serviços depois de aceitar recompensas em salas de bate-papo",
    "在聊天室滥用踢人/禁麦等管理权限" => "Abusar dos direitos de gerenciamento como chutar/banir em salas de bate-papo",
    "盗用他人信息" => "Roubar informações de outras pessoas",
    "冒充官方账号" => "Fingir ser uma conta oficial",
    "头像/昵称/签名含有广告/色情/违法信息" => "Contém propaganda/pornografia/informações ilegais em avatar/apelido/assinatura",
    "用户提现" => "Retirada do usuário",
    "私下买卖礼物" => "Comprar e vender presentes de forma privada",
    "未成年打赏" => "Dar recompensas sendo um minor",
    "金额诈骗" => "Fraude de valor",
    "金额异常" => "Valor abnormal",
    "收到打赏不服务" => "Não prestar serviço depois de aceiter recompensas",
    "提供违规服务" => "Oferecer serviços ilegais",
    "买卖礼物诈骗" => "Fraude na compra e venda de presentes",
    "违规代充" => "Fazer recarga em nome de outros ",
    "【罚款处罚】该账号由于【%s】，被官方处以罚款%s币的处罚，系统将会从您的账户余额自动扣取罚金。如对该处罚有异议，可联系客服进行申诉。" => "【Penalidade de Multa】Devido a [%s], a conta foi oficialmente multada em %s moedas e o sistema deduzirá automaticamente a multa do saldo da sua conta. Se você tiver alguma objeção à penalidade, entre em contato com o atendimento ao cliente para recorrer.",
    "【冻结通知】该账号由于【%s】，被官方处以冻结%s币的处理，系统将会从您账户余额自动执行金额冻结。如对该处罚有异议，可联系客服进行申诉。" => "【Congelamento de Conta】Devido a [%s], a conta está oficialmente sujeita ao congelamento de %s moedas, e o sistema congelará automaticamente o valor do saldo da sua conta. Se você tiver alguma objeção à penalidade, entre em contato com o atendimento ao cliente para recorrer.",
    "可消费余额" => "Saldo consumível",
    "收入余额" => "Saldo de renda",
    "可下单余额" => "Saldo disponível para fazer pedidos",
    "魅力值" => "Nível do encanto",
    "【官方赠送金额】官方赠送%s币，其中填补欠款%s币，增加%s%s币，请在我->钱包查收。" => "【Presente Oficial】O oficial doou %s moedas, entre as quais os atrasados ​​de %s moedas são compensadas e %s moedas de %s são adicionadas. Por favor, verifique-as em Meu->Carteira.",
    "【官方赠送金额】官方赠送%s币，增加%s%s币，请在我->钱包查收。" => "【Presente Oficial】O oficial doou %s moedas. Foi adicionado %s modedas de %s. Por favor, verifique-as em Meu->Carteira.",
    "【官方赠送】官方赠送魅力值%s，增加魅力值余额%s。" => "【Presente Oficial】O oficial presenteou o valor de encanto %s. O saldo do valor de encanto aumentou %s.",
    "10分钟" => "10 minutos",
    "30分钟" => "30 minutos",
    "1小时" => "1 hora",
    "2小时" => "2 horas",
    "4小时" => "4 horas",
    "8小时" => "8 horas",
    "12小时" => "12 horas",
    "1天" => "1 dia",
    "3天" => "3 dias",
    "7天" => "7 dias",
    "1个月" => "1 mês",
    "永久" => "Permanente",
    "聊天室管理规范" => "Gerenciamento de salas de bate-papo",
    "您的房间【%s】id（%s）因违反%s被封禁%s" => "A sua sala【%s】id (%s) foi banida por %s por cause de violar %s",
    "您的房间【%s】id（%s）已被解封" => "A sua sala【%s】id (%s) foi desbloqueada",
    "扰乱平台秩序" => "Interromper a ordem da plataforma",
    "恶意刷单" => "Fazenda de cliques maliciosa",
    "加入/怂恿他人加入竞争平台" => "Juntar-se/incentivar outros a se juntarem a plataformas concorrentes",
    "越过平台收取现金单" => "Ignorar a plataforma e aceitar pedidos em dinheiro.",
    "泄露闲时数据及用户隐私" => "Divulgação de dados de lazer e privacidade do usuário",
    "恶意诋毁平台" => "Difamar maliciosamente a plataforma",
    "恶意引导用户至第三方平台" => "Direcionar maliciosamente de usuários para plataformas de terceiros",
    "发布反动、政治类违法言论" => "Publicar comentários ilegais reacionários e políticos",
    "真人与图片严重不符" => "A pessoa real não combina com a na imagem",
    "服务与水平严重不符" => "Serviço oferecido não combina com o nível real",
    "欺诈用户导致服务未完成" => "Não concluir o serviço ao fraudar os usuários",
    "恶性竞争或恶意营销" => "Concorrência feroz ou marketing malicioso",
    "向用户索要订单外的额外费用" => "Pedir ao usuário cobranças adicionais além do pedido",
    "要求用户先确认完成或好评后才服务" => "Exigir que os usuários confirmem a conclusão ou elogiem antes de servir",
    "未按照订单时间和时长服务用户" => "Falha no atendimento aos usuários de acordo com o horário e a duração do pedido",
    "侮辱谩骂骚扰用户" => "Insultar e assediar usuários",
    "服务迟到早退私自离开等" => "Chegar tarde no serviço, sair mais cedo, sair em particular, etc.",
    "服务不专心频繁做其他事情" => "Serviço desatento frequentemente fazendo outras coisas",
    "真人或视频服务时形象邋遢、暴露" => "Ficar com imagem desleixada e reveladora no serviço ao vivo ou de vídeo",
    "同一用户禁止多帐号登录" => "É proibido de fazer login de várias contas por um mesmo usuário",
    "昵称还有广告，色情或违法信息" => "Apelidos contém anúncios, informações pornográficas ou ilegais",
    "个人简介含有广告，色情或违法信息" => "Perfil contém informações publicitárias, pornográficas ou ilegais",
    "发布毒品、博彩、投注等违法信息" => "Publicar informações ilegais como drogas, jogos, apostas",
    "不按资质及订单要求服务" => "Não oferecer serviços de acordo com as qualificações e os requisitos do pedido",
    "用户下单后不主动回复用户" => "Não tomar a iniciativa de responder ao usuário após que o mesmo fazer um pedido",
    "聊天室里对老板态度恶劣" => "Tratar o chefe de má atitude na sala de bate-papo",
    "在聊天室辱骂/攻击他人" => "Abusar/atacar outras pessoas em salas de bate-papo",
    "个人资料信息与身份认证信息不一致" => "As informações de dados pessoais não correspondem às informações de verificação de identidade.",
    "个人头像是网红/明星等网络来源图片" => "Avatares pessoais são imagens de fontes da Internet, como celebridades/estrelas",
    "买卖礼物" => "Comprar e vender presentes",
    "钻石套现" => "Transformar diamentes em dinheiro",
    "套现诈骗" => "Fraude de intercâmbio",
    "在聊天室违规表演" => "Agir ilegalmente em uma sala de bate-papo",
    "要挟大神提供订单以外的服务" => "Coagir mestres a fornecer serviços fora de pedidos",
    "协助大神恶意刷单" => "Ajudar mestres a realizar fazenda de cliques",
    "损害平台利益" => "Prejudicar os interesses da plataforma",
    "泄露他人隐私" => "Revelar a privacidade dos outros",
    "恶意发送第三方联系方式" => "Enviar informações de contato de terceiros maliciosamente",
    "侮辱谩骂、骚扰用户" => "Insultar e assediar usuários",
    "发布恶意链接" => "Postar links maliciosos",
    "发布引起观看不适的内容" => "Publicar conteúdo desconfortável",
    "多账号恶意扰乱平台秩序" => "Interromper maliciosamente a ordem da plataforma com várias contas",
    "恶意下单使大神降权" => "Fazer pedidos maliciosamente para derrubar o nível de mestre",
    "过期单太多" => "Ter muitos pedidos atrasados",
    "拒绝单太多" => "Ter muitos pedidos rejeitados",
    "被取消单太多" => "Ter muitos pedidos que foram cancelados",
    "系统性别与资料性别不一致" => "O sexo de sistema não corresponde ao sexo no perfil.",
    "您的提现信息未通过审核，银行卡号错误" => "Suas informações de retirada não foram aprovadas, porque o número do cartão bancário foi incorreto.",
    "您的提现信息未通过审核，银行户名错误" => "Suas informações de retirada não foram aprovadas, porque o nome da conta bancária foi incorreto.",
    "您的提现信息未通过审核，开户城市错误" => "Suas informações de retirada não foram aprovadas, porque a cidade de abertura de conta foi incorreta.",
    "您的提现信息未通过审核，开户支行名错误" => "Suas informações de retirada não foram aprovadas, porque o nome do banco filial emitente foi incorreto.",
    "您的提现信息未通过审核，银行开户支行名格式错误" => "Suas informações de retirada não foram aprovadas, porque o formato do nome do banco filial emitente foi incorreto.",
    "您的提现信息未通过审核，银行户名与身份认证姓名不一致" => "Suas informações de retirada não foram aprovadas, porque o nome da conta bancária não corresponde ao nome de identidade verificada.",
    "您的提现信息未通过审核，不支持该银行" => "Suas informações de retirada não foram aprovadas, porque este banco não é suportado.",
    "您的提现信息未通过审核，银行开户城市未填写省份" => "Suas informações de retirada não foram aprovadas devido à falta de informações de província para a cidade de abertura da conta bancária.",
    "您的提现信息未通过审核，银行开户地省份或者城市未按要求填写，正确的填写方式如湖北省武汉市" => "Suas informações de retirada não foram aprovadas. A província ou cidade de abertura da conta não foi preenchida como requerido. A forma correta de preenchimento por exemplo => Avenida Paulista, nº 550, São Paulo, cep => xxxxx.xxx, Brasil.",
    "您的提现信息未通过审核，支付宝账号不存在" => "Suas informações de retirada não foram aprovadas, porque a conta não existe.",
    "您的提现信息未通过审核，支付宝账号错误" => "Suas informações de retirada não foram aprovadas, porque o número da conta foi incorreta.",
    "您的提现信息未通过审核，支付宝账号不是主登录账号" => "Suas informações de retirada não foram aprovadas, porque a conta não é de login principal.",
    "您的提现信息未通过审核，未填写支付宝账号信息" => "Suas informações de retirada não foram aprovadas devido à falta de informações da conta.",
    "您的提现信息未通过审核，收款人名或姓错误" => "Suas informações de retirada não foram aprovadas, porque o nome ou sobrenome do beneficiário foi incorreto.",
    "您的提现信息未通过审核，街道城市省份邮编信息错误" => "Suas informações de retirada não foram aprovadas, porque há erros nas informações do código postal/da cidade/da rua. ",
	"您的身份认证未通过审核，身份证姓名与所填姓名不一致" => "Sua verificação de identidade não foi aprovada porque o nome na carteira de identidade foi inconsistente com o nome preenchido.",
	"您的身份认证未通过审核，身份证与个人头像不是同一个人" => "Sua verificação de identidade não foi aprovada porque o avatar pessoal foi inconsistente com a pessoa da carteira de identidade.",
	"您的身份认证未通过审核，身份证性别与资料性别不一致" => "Sua verificação de identidade não foi aprovada porque o genero na carteira de identidade foi inconsistente com o dos dados pessoais.",
	"您的身份认证未通过审核，所填身份证号无效" => "Sua verificação de identidade não foi aprovada porque o número de identificação inserido foi inválido.",
	"您的身份认证未通过审核，所填姓名无效" => "Sua verificação de identidade não foi aprovada porque o nome inserido foi inválido.",
	"您的身份认证未通过审核，非有效身份证" => "Sua verificação de identidade não foi aprovada porque o cartão de identidade está inválido.",
	"您的身份认证未通过审核，身份证过期" => "Sua verificação de identidade não foi aprovada porque o cartão de identidade expirou.",
	"您的身份认证未通过审核，身份证照片与手持身份证不一致" => "Sua verificação de identidade não foi aprovada porque a foto da carteira de identidade é inconsistente com a carteira de identidade em mãos.",
	"您的身份认证未通过审核，身份证正面照不清晰" => "Sua verificação de identidade não foi aprovada porque a foto frontal do documento de identidade não está clara.",
	"您的身份认证未通过审核，身份证反面照不清晰" => "Sua verificação de identidade não foi aprovada porque o verso da carteira de identidade não está claro.",
	"您的身份认证未通过审核，手持身份证照片中的人脸不清晰" => "Sua verificação de identidade não foi aprovada porque o rosto na foto com a carteira de identidade não está claro",
	"您的身份认证未通过审核，手持身份证照片中的身份证不清晰" => "Sua verificação de identidade não foi aprovada porque o cartão de identidade que contém na foto de segurando o cartão com mão não está claro",
	"您的身份认证未通过审核，身份证照片作假" => "Sua verificação de identidade não foi aprovada porque a foto de identidade é falsa.",
	"您的身份认证未通过审核，身份证正面照非手持拍摄" => "Sua verificação de identidade não foi aprovada porque a foto frontal da carteira de identidade não foi tirada segurando com mão",
	"您的身份认证未通过审核，身份证反面照非手持拍摄" => "Sua verificação de identidade não foi aprovada porque a foto de verso da carteira de identidade não foi tirada segurando com mão",
	"您的身份认证未通过审核，本人近期自拍照与身份证照片不是同一个人" => "Sua verificação de identidade não foi aprovada porque de selfie recente e de foto de identidade não são a mesma pessoa.",
	"您的身份认证未通过审核，自拍照不是正面清晰照" => "Sua verificação de identidade não foi aprovada porque a foto selfie não é uma foto frontal clara.",
	"您的身份认证未通过审核，身份认证与技能封面图中的人不是同一个人" => "Sua verificação de identidade não foi aprovada porque a pessoa de verificação de identidade não é a mesma pessoa na imagem da capa da habilidade.",
	"您的身份认证未通过审核，身份证年龄未满18周岁" => "Sua verificação de identidade não foi aprovada porque e a idade da carteira de identidade é menor de 18 anos",
	"您的身份认证未通过审核，同一身份证不能多账号使用" => "Sua verificação de identidade não foi aprovada porque o mesmo cartão de identidade não pode ser usado por várias contas",
	"您的身份认证未通过审核，身份证年龄不能超过50岁" => "Sua verificação de identidade não foi aprovada porque a idade da carteira de identidade não pode exceder 50 anos",
	"您的身份认证未通过审核，请按示例图提交" => "Sua verificação de identidade não foi aprovada. Por favor envie-a de acordo com a imagem de amostra.",
	"经审核，来自%s的%s币收益已解除临时冻结，可正常消费" => "Após a revisão, a receita de moedas de %s de %s foi liberada do congelamento temporário e pode ser consumida normalmente.",
    "加人气申请已被拒绝" => "O pedido de aumentar popularidade foi rejeitado.",
    "加人气申请已通过" => "O pedido de aumentar popularidade foi aprovado.",
    "您已被移出%s公会，您可申请加入其他公会，点击加入公会>>" => "Você foi removido da guilda%s, você pode se inscrever para entrar em outras guildas, clique para entrar na guilda >>",
    "加入公会" => "Juntar-se à guilda",
    "您获得魅力值" => "Você ganhou valor de encanto",
    "您的个人工作室申请资料未通过审核，原因【%s】" => "Suas informações de inscrição para estúdio pessoal não foram aprovadas por causa de [%s].",
    "照片人脸不清晰" => "O rosto na foto não está nítido.",
    "委托声明照片不是手持拍摄" => "Foto da declaração de autorização não era segurada de mão.",
    "委托声明拍摄不清晰" => "A foto de declaração de autorização não é nítida suficiente.",
    "申请个人工作室用的身份证与身份认证证件不一致" => "O cartão de identidade usado para solicitar o estúdio pessoal foi inconsistente com o cartão usado na verificação de identidade.",
    "手机号无效" => "Número de telefone inválido",
    "委托声明中本人身份证号有误" => "O número da identidade na declaração de autorização foi incorreto.",
    "委托声明本中人姓名有误" => "O nome da identidade na declaração de autorização foi incorreto.",
    "委托声明中本人身份证号与申请资料不一致" => "O número da identidade na declaração de autorização foi inconsistente com o nas informações sobre a inscrição.",
    "委托声明中本人姓名与申请资料不一致" => "O nome da identidade na declaração de autorização foi inconsistente com o nas informações sobre a inscrição.",
    "委托声明中被委托人姓名有误" => "O nome do destinatário na declaração de autorização foi incorreto.",
    "委托声明中本人身份证照片不清晰" => "A foto do cartão de identidade na declaração de autorização não está nítida.",
    "委托声明中被委托人身份证号有误，请查看示例" => "O número da identidade do destinatário na declaração de autorização foi incorreto, por favor consulte o exemplo.",
    "委托声明中被委托人单位信息有误，请查看示例" => "As informações de trabalho do destinatário na declaração de autorização foi incorreto, por favor consulte o exemplo.",
    "委托声明文字信息有误，请查看示例" => "As informações de texto na declaração de autorização foram incorretas, por favor consulte o exemplo.",
    "委托视频拍摄不清晰" => "A filmagem do vídeo de autorização não está clara.",
    "委托视频声音不清晰" => "O som no vídeo de autorização não está claro.",
    "委托视频中委托书文字不清晰" => "Os textos no vídeo de autorização não estão nítidos.",
    "委托视频中所读文字有误，请参照视频示例拍摄" => "Os textos lidos no vídeo de autorização estavam incorretos. Por favor grave o vídeo como no exemplo.",
    "本人身份证照片不完整清晰" => "A sua foto no cartão de identidade não está completa e clara.",
    "本人身份证已过有效期" => "O seu cartão de identidade expirou.",
    "财务人员身份证照片不完整清晰" => "A foto no cartão de identidade do responsável financeiro não está completa e clara.",
    "财务人员身份证已过有效期" => "O cartão de identidade do responsável financeiro expirou.",
    "财务人员不能是本人" => "O responsável financeiro não pode ser você mesmo.",
    "财务人员年龄应是18-55岁" => "O responsável financeiro deve ter de 18 a 55 anos.",
    "申请资料不完整" => "Informações sobre a inscrição não estão completas.",
    "您的个人工作室已办理成功" => "Seu estúdio pessoal foi processado com sucesso.",
    "您加入工作室的申请未通过，请重新操作或联系客服" => "Sua inscrição para ingressar no estúdio não foi aprovada. Tente novamente ou entre em contato com o atendimento ao cliente.",
    "您加入的原工作室已注销，请进入申请提现页重新加入工作室" => "O estúdio original em que você ingressou foi cancelado. Por favor, acesse a página de solicitação de retirada para ingressar no estúdio novamente.",
    "您已成功加入工作室" => "Você ingressou no estúdio com sucesso.",
    "您加入工作室的申请已被拒绝，请联系客服" => "A sua solicitação de ingressar no estúdio foi rejeitada. Por favor, entre em contato com o atendimento ao cliente.",
    "未上传符合要求的视频" => "Não foi enviado o vídeo qualificado.",
    "自拍视频与头像不是同一个人" => "A pessoa no vídeo selfie não é a mesma pessoa que no avatar.",
    "自拍视频与技能封面不是同一个人" => "A pessoa no vídeo selfie não é a mesma pessoa que na capa de habilidade.",
    "禁止一个人申请多个技能认证账号" => "É proibido que uma pessoa solicite várias contas de certificação de habilidades.",
    "个人资料与其他人重复" => "Perfil repetido com o de outras pessoas.",
    "性别与资料性别不一致" => "O sexo não corresponde ao sexo no perfil.",
    "用户要求关闭技能" => "O usuário pediu para desativar a habilidade.",
    "被多名用户投诉服务不满意" => "O serviço foi reclamado por vários usuários como \"Não satisfeito\".",
    "头像不是本人正面清晰照" => "O avatar não é uma foto frontal e claro de você próprio.",
    "技能封面不符合要求" => "A capa de habilidade não atende aos requisitos.",
    "技能音频不符合要求" => "O áudio da habilidade não atende aos requisitos.",
    "技能说明信息不符合要求" => "As informações da descrição da habilidade não atendem aos requisitos.",
    "段位不符合要求" => "O nível não atende aos requisitos.",
    "未进行人工考核" => "Não fez revisão humana ainda.",
    "未通过人工考核" => "Não foi aprovada pela revisão humana.",
    "昵称/签名含有色情/广告等违规信息" => "O apelido/assinatura contém informações ilegais como pornografia/publicidade.",
    "涉嫌提供色情等违规服务" => "Suspeito de fornecer pornografia e outros serviços ilegais.",
    "视频含有色情，广告等信息" => "O vídeo contém informações ilegais como pornografia, publicidade etc.",
    "恭喜您，您的视频通过了认证，您已成为视频认证用户，可开通视频和线下服务。" => "Parabéns, seu vídeo foi aprovado na certificação. Você se tornou um usuário certificado de vídeo e pode ativar serviços de vídeo e de off-line.",
    "含有涉政信息" => "Contém informações políticas.",
    "含有涉黄信息" => "Contém informações pornográficas.",
    "含有广告信息" => "Contém informações de publicidade.",
    "含有违规信息" => "Contém informações ilegais.",
    "含有严重涉政信息" => "Contém informações muito envolvidas na política.",
    "含有严重涉黄信息" => "Contém coisas muito envolvidas na pornografia.",
    "含有严重广告信息" => "Contém informações muito envolvidas na publicidade.",
    "含有严重违规信息" => "Contém informações muito ilegais.",
    "头像非本人正面清晰照" => "O avatar não é uma foto frontal e claro de você próprio.",
    "图片来源网络" => "Rede de origem da imagem",
    "机审通过" => "Aprovados na revisão por máquina.",
    "人工审核" => "Revisão humana",
    "中东图片人工审核" => "Revisão humana de fotos no Oriente Médio",
    "人工审核 => 机检失败" => "Revisão humana => Falhou no teste por máquina.",
    "广告 => 包含联系方式" => "Anúncio => Incluir detalhes de contato.",
    "图片:含有违规内容" => "Imagem => Incluir conteúdos ilegais.",
    "与其他用户头像相似度过高" => "Muito semelhante a avatares de outros usuários",
    "您的昵称审核不通过已被置为无效昵称，原因：含有广告信息" => "Seu apelido falhou de ser aprovado e foi definido como um apelido inválido porque => contém informações de publicidade.",
    "您的昵称审核不通过已被置为无效昵称，原因：含有色情信息" => "Seu apelido falhou de ser aprovado e foi definido como um apelido inválido porque => contém informações pornográficas.",
    "您的昵称审核不通过已被置为无效昵称，原因：含有违法信息" => "Seu apelido falhou de ser aprovado e foi definido como um apelido inválido porque => contém informações ilegais.",
    "您的昵称审核不通过已被置为无效昵称，原因：含有违规信息" => "Seu apelido falhou de ser aprovado e foi definido como um apelido inválido porque => contém informações ilegais.",
    "您的昵称审核不通过已被置为无效昵称，原因：含有涉政信息" => "Seu apelido falhou de ser aprovado e foi definido como um apelido inválido porque => contém informações políticas.",
    "您的昵称审核不通过已被置为无效昵称，原因：含有第三方联系方式" => "Seu apelido falhou de ser aprovado e foi definido como um apelido inválido porque => contém detalhes de contato de terceiros.",
    "您的签名审核不通过已被置为无效签名，原因：含有广告信息" => "Sua assinatura falhou de ser aprovada e foi definida como uma assinatura inválida porque => contém informações de publicidade.",
    "您的签名审核不通过已被置为无效签名，原因：含有色情信息" => "Sua assinatura falhou de ser aprovada e foi definida como assinatura inválida porque => contém informações pornográficas.",
    "您的签名审核不通过已被置为无效签名，原因：含有违法信息" => "Sua assinatura falhou de ser aprovada e foi definida como assinatura inválida porque => contém informações ilegais.",
    "您的签名审核不通过已被置为无效签名，原因：含有违规信息" => "Sua assinatura falhou de ser aprovada e foi definida como assinatura inválida porque => contém informações ilegais.",
    "您的签名审核不通过已被置为无效签名，原因：含有涉政信息" => "Sua assinatura falhou de ser aprovada e foi definida como uma assinatura inválida porque => contém informações políticas.",
    "您的签名审核不通过已被置为无效签名，原因：含有第三方联系方式" => "Sua assinatura falhou de ser aprovada e foi definida como assinatura inválida porque => contém detalhes de contato de terceiros.",
    "您的头像未通过审核，原因：个人头像不是本人正面清晰照" => "Seu avatar não foi aprovado porque => o avatar não foi a sua foto frontal clara.",
    "您的头像未通过审核，原因：个人头像照片拍摄不美观" => "Seu avatar não foi aprovado porque => a foto do avatar não foi aprópria.",
    "您的头像未通过审核，原因：个人头像人物比例不协调" => "Seu avatar não foi aprovado por cause de proporções inconsistentes do caráter na foto.",
    "您的头像未通过审核，原因：个人头像画质像素过低" => "Seu avatar não foi aprovado porque => o pixel de qualidade da imagem do perfil é muito baixo.",
    "您的头像未通过审核，原因：个人头像非正面清晰无遮挡照片" => "Seu avatar não foi aprovado porque => Não foi uma foto clara e desobstruída da frente.",
    "您的头像未通过审核，原因：个人头像PS过度" => "Seu avatar não foi aprovado porque => a foto do avatar foi retocada demais.",
    "您的头像未通过审核，原因：个人头像为网红、明星等网络来源照片。如头像为本人真实照片，请联系客服进行人工认证" => "Seu avatar não foi aprovado porque => o avatar usou uma foto de fontes da Internet, como celebridades e influentes. Se o avatar for uma foto real sua, entre em contato com o atendimento ao cliente para verificação humana.",
    "您的头像未通过审核，原因：个人头像为拼接图" => "Seu avatar não foi aprovado porque => a foto do avatar foi um mosaico.",
    "您的头像未通过审核，原因：个人头像为与他人的合照" => "Seu avatar não foi aprovado porque => a foto do avatar foi uma foto de grupo com outras pessoas.",
    "您的头像未通过审核，原因：个人头像涉及暴露、含性暗示等违规行为" => "Seu avatar não foi aprovado porque => contém informações envolvendo violações como exposição, implicação sexual, etc.",
    "您的头像未通过审核，原因：个人头像不能为黑白" => "Seu avatar não foi aprovado porque => a foto do avatar não pode ser em preto e branco.",
    "您的头像未通过审核，原因：个人头像不能有大量空白" => "Seu avatar não foi aprovado porque => a foto do avatar não pode ter muito espaço em branco.",
    "您的头像未通过审核，原因：个人头像与性别不符" => "Seu avatar não foi aprovado porque => a foto não corresponde ao seu sexo.",
    "您的头像未通过审核，原因：含有色情信息" => "Seu avatar não foi aprovado porque => a foto contém informações pornográficas.",
    "您的头像未通过审核，原因：含有广告信息" => "Seu avatar não foi aprovado porque => a foto contém informações de publicidade.",
    "您的头像未通过审核，原因：含有暴力信息" => "Seu avatar não foi aprovado porque => a foto contém informações violentas.",
    "您的头像未通过审核，原因：含有违法信息" => "Seu avatar não foi aprovado porque => a foto contém informações ilegais.",
    "您的头像未通过审核，原因：含有违规信息" => "Seu avatar não foi aprovado porque => a foto contém informações ilegais.",
    "您的头像未通过审核，原因：含有涉政信息" => "Seu avatar não foi aprovado porque => a foto contém informações políticas.",
    "您的头像未通过审核，原因：含有第三方联系方式" => "Seu avatar não foi aprovado porque => a foto contém contatos de terceiros.",
    "您的头像被删除，原因：个人头像不是本人正面清晰照" => "Seu avatar foi excluído porque => a foto do avatar não foi a sua foto frontal clara.",
    "您的头像被删除，原因：头像与性别不一致，请上传新的头像" => "Seu avatar foi excluído porque => o avatar não corresponde ao seu sexo. Por favor, envie um novo avatar.",
    "您的头像被删除，原因：头像含有色情信息，请上传新的头像" => "Seu avatar foi excluído porque => o avatar contém informações pornográficas. Por favor, envie um novo avatar.",
    "您的头像被删除，原因：头像含有违规信息，请上传新的头像" => "Seu avatar foi excluído porque => o avatar contém informações ilegais. Por favor, envie um novo avatar.",
    "您的头像被删除，原因：头像含有违法信息，请上传新的头像" => "Seu avatar foi excluído porque => o avatar contém informações ilegais. Por favor, envie um novo avatar.",
    "您的头像被删除，原因：头像含有涉政信息，请上传新的头像" => "Seu avatar foi excluído porque => o avatar contém informações políticas. Por favor, envie um novo avatar.",
    "您的头像被删除，原因：头像含有第三方联系方式，请上传新的头像" => "Seu avatar foi excluído porque => o avatar contém contatos de terceiros. Por favor, envie um novo avatar.",
    "您的形象照被删除，原因：形象照含有色情信息" => "Sua foto da imagem foi excluída porque => a foto contém informações pornográficas.",
    "您的形象照被删除，原因：形象照含有违规信息" => "Sua foto de imagem foi excluída porque => a foto contém informações ilegais.",
    "您的形象照被删除，原因：形象照含有违法信息" => "Sua foto de imagem foi excluída porque => a foto contém informações ilegais.",
    "您的形象照被删除，原因：形象照含有涉政信息" => "Sua foto da imagem foi excluída porque => a foto contém informações políticas.",
    "您的形象照被删除，原因：形象照含有第三方联系方式" => "Sua foto da imagem foi excluída porque => a foto contém contatos de terceiros.",
    "您的形象照被删除，原因：形象照不是本人清晰照片" => "Sua foto da imagem foi excluída porque => a foto não foi a sua própria foto clara.",
    "您提交的头像未通过审核。请勿上传含有色情、暴力、涉政、反动、广告等违法违规内容的头像。" => "O avatar que você enviou não foi aprovado. Por favor, não faça upload de avatares que contenham conteúdo pornográfico, violento, político, reacionário, publicitário e outros conteúdos ilegais.",
    "恭喜您通过了头像审核！" => "Parabéns por passar na avaliação do avatar!",
    "您提交的形象照未通过审核。请勿提交含有色情、暴力等违规内容的图片。" => "A foto da imagem que você enviou não foi revisada. Por favor, não envie imagens com conteúdo ilegal, como pornografia, violência, etc.",
    "由于您提交的头像/形象照/昵称/签名违规，您之后提交的个人资料都将被审核通过后才能生效" => "Devido à violação do avatar/foto da imagem/apelido/assinatura que você enviou, as informações pessoais enviadas posteriormente serão revisadas e aprovadas antes de entrarem em vigor.",
    "昵称" => "Nome",
    "您修改%s的权限已恢复" => "Sua autorização para modifica %s foi restaurada.",
    "您提交的%s违规，%s天内禁止修改" => "%s que você enviou violou as regras, pelo que a modificação será proibida dentro de %s dias.",
    "房间公告" => "Anúncio da sala",
    "房间名字" => "Nome da sala",
    "您因多次提交违规%s，被处以限制修改%s天的处罚，%s天内修改的%s均须先通过审核才能显示" => "Você está sujeito a uma penalidade por restringir a modificação por %s dias devido a vários envios de %s que violou as regras. A modificação de %s em %s dias deve ser revisada antes de ser exibida.",
    "签名" => "Assinatura",
    "头像" => "Avatar",
    "恢复先发后审" => "Voltar para publicar antes da revisão.",
    "含有暴力信息" => "Contém informações violentas.",
    "您的房间头像审核不通过已被重置，原因：含有色情信息" => "O avatar da sua sala falhou de ser aprovado e foi redefinido porque => contém informações pornográficas.",
    "您的房间头像审核不通过已被重置，原因：含有广告信息" => "O avatar da sua sala falhou de ser aprovado e foi redefinido porque => contém informações de publicidade.",
    "您的房间头像审核不通过已被重置，原因：含有暴力信息" => "O avatar da sua sala falhou de ser aprovado e foi redefinido porque => contém informações violentas.",
    "您的房间头像审核不通过已被重置，原因：含有违法信息" => "O avatar da sua sala falhou de ser aprovado e foi redefinido porque => contém informações ilegais.",
    "您的房间头像审核不通过已被重置，原因：含有违规信息" => "O avatar da sua sala falhou de ser aprovado e foi redefinido porque => contém informações ilegais.",
    "您的房间名审核不通过已被重置，原因：含有广告信息" => "O nome da sua sala falhou de ser aprovado e foi redefinido porque => contém informações de publicidade.",
    "您的房间名审核不通过已被重置，原因：含有色情信息" => "O nome da sua sala falhou de ser aprovado e foi redefinido porque => contém informações pornográficas.",
    "您的房间名审核不通过已被重置，原因：含有违法信息" => "O nome da sua sala falhou de ser aprovado e foi redefinido porque => contém informações ilegais.",
    "您的房间名审核不通过已被重置，原因：含有违规信息" => "O nome da sua sala falhou de ser aprovado e foi redefinido porque => contém informações ilegais.",
    "您的房间名审核不通过已被重置，原因：含有暴力信息" => "O nome da sua sala falhou de ser aprovado e foi redefinido porque => contém informações violentas.",
    "您的房间公告审核不通过已被置为空，原因：含有广告信息" => "O anúncio da sua sala falhou ao ser aprovado e foi definido como vazio porque => contém informações de publicidade.",
    "您的房间公告审核不通过已被置为空，原因：含有色情信息" => "O anúncio da sua sala falhou ao ser aprovado e foi definido como vazio porque => contém informações pornográficas.",
    "您的房间公告审核不通过已被置为空，原因：含有违法信息" => "O anúncio da sua sala falhou ao ser aprovado e foi definido como vazio porque => contém informações ilegais.",
    "您的房间公告审核不通过已被置为空，原因：含有违规信息" => "O anúncio da sua sala falhou ao ser aprovado e foi definido como vazio porque => contém informações ilegais.",
    "您的房间公告审核不通过已被置为空，原因：含有暴力信息" => "O anúncio da sua sala falhou ao ser aprovado e foi definido como vazio porque => contém informações violentas.",
    "您的房间%s(房间ID)因多次提交违规%s，被处以限制修改%s天的处罚，%s天内修改的%s均须先通过审核才能显示" => "A sua sala %s (ID da sala) está sujeita uma penalidade por restringir a modificação por %s dias devido a vários envios de %s que violou as regras. A modificação de %s em %s dias deve ser revisada antes de ser exibida.",
    "您的%s技能主题已被修改，原因：含有广告信息" => "O tema da sua habilidade %s foi modificado por causa de conter informações de publicidade.",
    "您的%s技能主题已被修改，原因：含有违法信息" => "O tema da sua habilidade %s foi modificado por causa de conter informações ilegais.",
    "您的%s技能主题已被修改，原因：含有违规信息" => "O tema da sua habilidade %s foi modificado por causa de conter informações ilegais.",
    "您的%s技能主题已被修改，原因：含有色情信息" => "O tema da sua habilidade %s foi modificado por causa de conter informações pornográficas.",
    "您修改%s技能主题的权限已恢复" => "Sua autorização para modificar o tema da habilidade %s foi restaurada.",
    "您提交的%s技能主题违规，%s天内禁止修改" => "O tema da habilidade %s que você enviou violou as regras, pelo que a modificação será proibida dentro de %s dias.",
    "恭喜您已通过资料认证！" => "Parabéns por passar na verificação de perfil!",
    "您的资料认证未通过审核，原因：" => "A verificação do seu perfil não foi aprovada porque:",
    "该功能暂不开放申请" => "Esse recurso não está disponível para solicitar no momento.",
    "用户要求关闭资料认证" => "O usuário solicita para desativar a verificação de perfil.",
    "个人头像不是本人正面清晰照" => "A foto de perfil não é uma foto frontal e claro de você próprio.",
    "个人头像照片拍摄不美观" => "A foto de perfil não é apropriada.",
    "个人头像人物比例不协调" => " Proporção do carácter foi inconsistente na foto de perfil.",
    "个人头像画质像素过低" => "O pixel de qualidade da foto de perfil é muito baixo.",
    "个人头像非正面清晰无遮挡照片" => "A foto de perfil não foi uma foto clara e desobstruída da frente.",
    "个人头像PS过度" => "A foto de perfil foi retocada demais.",
    "个人头像为网红、明星等网络来源照片。如头像为本人真实照片，请联系客服进行人工认证" => " A sua foto de perfil usou uma foto de fontes da Internet, como celebridades e influentes. Se a foto for uma foto real sua, entre em contato com o atendimento ao cliente para verificação humana.",
    "个人头像为拼接图" => " A sua foto de perfil foi um mosaico.",
    "个人头像为与他人的合照" => "A sua foto de perfil foi uma foto de grupo com outras pessoas.",
    "个人头像涉及暴露、含性暗示等违规行为" => "A sua foto de perfil contém informações ilegais como exposição, implicação sexual, etc.",
    "个人头像不能为黑白" => "A foto do perfil não pode ser em preto e branco.",
    "个人头像不能有大量空白" => "A foto de perfil não pode ter muito espaço em branco.",
    "个人头像与性别不符" => "A sua foto de perfil não corresponde ao seu sexo.",
    "您好，工作人员正在处理您【%s】对【%s】【%s】的举报" => "Olá, o responsável está processando seu relatório 【%s】sobre【%s】【%s】",
    "您好，您【%s】对【%s】【%s】的举报已处理" => "Olá, o seu relatório【%s】sobre 【%s】【%s】foi processado",
    "您好，由于【%s】，您【%s】对【%s】【%s】的举报已被驳回" => "Olá, devido a 【%s】, seu relatório【%s】para sobre 【%s】【%s】foi descartado",
    "举报的行为未违规" => "O comportamento relatado não violou regras",
    "举报证据不足" => "Evidências está insuficientes para relatar",
    "第三方平台资料不能作为有效证据" => "Os dados de terceira plataforma não podem ser usadas como evidência válida.",
    "重复举报" => "Repetir fazer relatórios",
    "非当事人举报" => "Fazer relatórios sendo não-partes",
    "头像，视频含有色情，广告等信息" => "Contém informações ilegais como pornografia e publicidade no avatar ou vídeos",
    "频繁骚然TA人" => "Assediar os outros com frequência",
    "您已被禁止在闲时里和人聊天，因为您被多名用户举报，举报原因：涉嫌诈骗" => "Você foi proibido de conversar com pessoas em seu tempo livre, porque foi denunciado por vários usuários com a razão de ser suspeito de fraude.",
    "您已被禁止在闲时里和人聊天，因为您被多名用户举报，举报原因：涉嫌发布政治敏感信息" => "Você foi proibido de conversar com pessoas em seu tempo livre, porque foi denunciado por vários usuários com a razão de postar informações sensitivas em relação à política.",
    "您已被禁止在闲时里和人聊天，因为您被多名用户举报，举报原因：涉嫌侵权" => "Você foi proibido de conversar com pessoas em seu tempo livre, porque foi denunciado por vários usuários com a razão de ser suspeito de infração.",
    "您已被禁止在闲时里和人聊天，因为您被多名用户举报，举报原因：涉嫌侮辱诋毁他人" => "Você foi proibido de conversar com pessoas em seu tempo livre, porque foi denunciado por vários usuários com a razão de ser suspeito de insultar os outros.",
    "您已被禁止在闲时里和人聊天，因为您被多名用户举报，举报原因：涉嫌发布色情信息" => "Você foi proibido de conversar com pessoas em seu tempo livre, porque foi denunciado por vários usuários com a razão de postar informações pornográficas.",
    "您已被禁止在闲时里和人聊天，因为您被多名用户举报，举报原因：涉嫌发布广告信息" => "Você foi proibido de conversar com pessoas em seu tempo livre, porque foi denunciado por vários usuários com a razão de postar informações de publicidade.",
    "您已被禁止在闲时里和人聊天，因为您被多名用户举报，举报原因：涉嫌绕开平台走现金单" => "Você foi proibido de conversar com pessoas em seu tempo livre, porque foi denunciado por vários usuários com a razão de ser suspeito de burlar a plataforma e receber recibos em dinheiro.",
    "您已被禁止在闲时里和人聊天，因为您被多名用户举报，举报原因：涉嫌频繁骚然他人" => "Você foi proibido de conversar com pessoas em seu tempo livre, porque foi denunciado por vários usuários com a razão de assediar os outros com frequência.",
    "您提交的家族封面未通过审核。请勿上传含有色情、暴力、涉政、反动、广告等违法违规内容的封面。" => "A capa de família que você enviou não foi aprovada. Por favor, não faça upload de capas que contenham conteúdo pornográfico, violento, político, reacionário, publicitário e outros conteúdos ilegais.",
    "恭喜您通过了家族封面审核！" => "Parabéns por passar na revisão da capa da família!",
    "您的家族名字审核不通过已被置为无效家族名字，原因：含有广告信息" => "O nome da sua família falhou de ser aprovado e foi definido como nome inválido porque => contém informações de publicidade.",
    "您的家族名字审核不通过已被置为无效家族名字，原因：含有色情信息" => "O nome da sua família falhou de ser aprovado e foi definido como nome inválido porque => contém informações pornográficas.",
    "您的家族名字审核不通过已被置为无效家族名字，原因：含有违法信息" => "O nome da sua família falhou de ser aprovado e foi definido como nome inválido porque => contém informações ilegais.",
    "您的家族名字审核不通过已被置为无效家族名字，原因：含有违规信息" => "O nome da sua família falhou de ser aprovado e foi definido como nome inválido porque => contém informações ilegais.",
    "您的家族简介审核不通过已被置为空，原因：含有广告信息" => "A introdução da sua família falhou ao ser aprovada e foi definida como vazio porque => contém informações de publicidade.",
    "您的家族简介审核不通过已被置为空，原因：含有色情信息" => "A introdução da sua família falhou ao ser aprovada e foi definida como vazio porque => contém informações pornográficas.",
    "您的家族简介审核不通过已被置为空，原因：含有违法信息" => "A introdução da sua família falhou ao ser aprovada e foi definida como vazio porque => contém informações ilegais.",
    "您的家族简介审核不通过已被置为空，原因：含有违规信息" => "A introdução da sua família falhou ao ser aprovada e foi definida como vazio porque => contém informações ilegais.",
    "您的家族封面未通过审核，原因：含有色情信息" => "A capa da sua família não foi aprovada porque => contém informações pornográficas.",
    "您的家族封面未通过审核，原因：含有广告信息" => "A capa da sua família não foi aprovada porque => contém informações de publicidade.",
    "您的家族封面未通过审核，原因：含有暴力信息" => "A capa da sua família não foi aprovada porque => contém informações violentas.",
    "您的家族封面未通过审核，原因：含有违法信息" => "A capa da sua família não foi aprovada porque => contém informações ilegais.",
    "您的家族封面未通过审核，原因：含有违规信息" => "A capa da sua família não foi aprovada porque => contém informações ilegais.",
    "您的粉丝铭牌【%s】未通过审核，请修改后重新提交" => "Seu crachá de fãs【%s】falhou ao ser aprovado, revise e reenvie por favor.",
    "您的粉丝铭牌【%s】已通过审核" => "Seu crachá de fãs【%s】foi aprovado com sucesso.",
    "包含敏感词" => "contém palavras sensíveis",
    "包含政治敏感内容" => "contém conteúdo politicamente sensível",
    "包含辱骂内容" => "contém conteúdo abusivo",
    "包含涉黄信息" => "Contém informações pornográficas",
    "包含广告信息" => "Contém informações de publicidade",
    "包含违规信息" => "Contém informações ilegais",
    "您的头像因%s未通过审核，已被清空" => "Seu avatar não foi aprovado por cause de %s e foi limpado.",
    "您的形象照因%s, 已删除" => "Sua foto de imagem foi excluída por cause de %s",
    "名字" => "Nome",
    "无名氏" => "Anônimo",
    "您的%s%s因%s, 已经清空" => "Seu %s %s foi limpado por cause de %s",
    "介绍" => "Introdução",
    "我的家族我做主" => "Eu sou o mestre da minha família",
    "您的家族[%s]的%s因%s, 已经重置" => "%s da sua família [%s] foi redefinido por cause de %s",
    "您的群组[%s]的%s因%s, 已经重置" => "%s do seu grupo [%s] foi redefinido por cause de %s",
    "公告" => "Anúncios",
    "我的房间我做主" => "Eu sou o mestre da minha sala",
    "您的房间[%s]的%s因%s, 已经重置" => "%s da sua sala [%s] foi redefinido por cause de %s",
    "你已成功退出公会(公会ID:%s)" => "Você saiu da guilda com sucesso (ID da guilda:%s)",
    "因您逾期未审核公会成员（ID:%s）的退会申请，该成员已自动退会" => "O membro da guilda (ID => %s) saiu automaticamente porque você não revisou o pedido de sair dele",
    "公会成员%s(ID:%s)支付退会费已满30天，退会成功" => "O membro da guilda %s (ID:%s) pagou a taxa de saída por 30 dias e a saída foi sucedida",
    "你被罚款%s币，原因：" => "Você é multado em %s moedas porque => ",
    "你与%s的合作代言关系已被解除" => "Sua cooperação de endosso com %s foi encerrada",
    "银行卡号错误" => "Número de cartão bancário errado",
    "银行户名错误" => "Nome da conta bancária errado",
    "开户城市错误" => "Cidade de abertura da conta errada",
    "开户支行名错误" => "Nome do banco filial emitente errado",
    "银行户名与身份认证姓名不一致" => "O nome da conta bancária não corresponde ao nome de verificação de identidade.",
    "不支持该银行" => "Esse banco não é suportado.",
    "支付宝账号错误" => "Número da conta do Alipay foi incorreto.",
    "账号处于封禁状态禁止提现" => "A conta está bloqueada pelo que é proibido de fazer retirada.",
    "请联系payoneer客服咨询" => "Por favor, entre em contato com o atendimento ao cliente de payoneer para consultar.",
    "银行卡信息错误，请检查姓名、卡号、开户行是否正确" => "As informações do cartão bancário estão erradas. Por favor, verifique se o nome, número do cartão e banco emissor estão corretos.",
    "银行卡II、III类卡超限额" => "Cartão bancário de II, III estão excedendo o limite",
    "支付宝账号有误" => "Número da conta do Alipay foi incorreto.",
    "支付宝账号未实名" => "Não foi verificado o nome real da conta do Alipay",
    "支付宝账号已注销" => "A conta Alipay foi excluída",
    "支付宝账号不符合监管部门要求，未补充身份信息" => "A conta Alipay não atende aos requisitos das autoridades reguladoras e as informações de identidade não foram complementadas",
    "您%s申请提现%s幣提现失败，%s提现资金已返还到您的账户，请确保提现账号正常后可再次申请提现" => "Sua solicitação de %s de retirada de moedas de %s falhou e os fundos de retirada de %s foram devolvidos à sua conta. Certifique-se de que a conta de retirada está normal antes de solicitar a retirada novamente.",
    "原因：%s。" => "Razão => %s.",
    "违反公会管理条例" => "Violar os regulamentos de gerenciamento da guilda.",
    "经审核，您%s充值的%s风险幣为违规收益已被冻结" => "Após a análise, a moeda de risco %s que você recarregou em %s foi uma renda ilegal e está congelada.",
    "经审核，来自%s的%s风险币为违规收益，已被冻结" => "Após a revisão, moeda de risco %s de %s foi renda ilegal e está congelada.",
    "【罚款处罚】该账号由于【%s】，被官方处以罚款%s钻石的处罚，系统将会从您的账户余额自动扣取罚金。如对该处罚有异议，可联系客服进行申诉。" => "【Penalidade de Multa】Devido a [%s], a conta foi oficialmente multada em %s diamantes e o sistema deduzirá automaticamente a multa do saldo da sua conta. Se você tiver alguma objeção à penalidade, entre em contato com o atendimento ao cliente para recorrer.",
    "【冻结通知】该账号由于【%s】，被官方处以冻结%s钻石的处理，系统将会从您账户余额自动执行金额冻结。如对该处罚有异议，可联系客服进行申诉。" => "【Congelamento de Conta】Devido a [%s], a conta está oficialmente sujeita ao congelamento de %s diamantes, e o sistema congelará automaticamente o valor do saldo da sua conta. Se você tiver alguma objeção à penalidade, entre em contato com o atendimento ao cliente para recorrer.",
    "【官方赠送金额】官方赠送%s钻石，其中填补欠款%s钻石，增加%s%s钻石，请在我->钱包查收。" => "【Presente Oficial】O oficial doou %s diamantes, entre as quais os atrasados ​​de %s diamantes são compensados e %s diamantes de %s são adicionadas. Por favor, verifique-as em Meu->Carteira.",
    "【官方赠送金额】官方赠送%s钻石，增加%s%s钻石，请在我->钱包查收。" => "【Presente Oficial】O oficial doou %s diamantes. Foi adicionado %s diamantes de %s. Por favor, verifique-as em Meu->Carteira.",
    "您%s申请提现%s钻石提现失败，%s提现资金已返还到您的账户，请确保提现账号正常后可再次申请提现" => "Sua solicitação de retirada de %s diamantes em %s falhou e os fundos de retirada de %s foram devolvidos à sua conta. Certifique-se de que a conta de retirada está normal antes de solicitar a retirada novamente.",
    "您%s申请电话卡提现%s钻石提现失败，钻石已退还，%s" => "O seu pedido em %s de retirada de recarga de celular em %s diamantes falhou, e os diamantes já foram devolvidos à sua conta, %s",
    "%s申请电话卡提现%s钻石，话费已到账，请查收" => "%s soliciou a retirada de recarga de celular em %s diamantes, os créditos já chegaram ao chip, por favor verifique.",
    "经审核，您%s充值的%s钻石为违规收益已被冻结" => "Após a análise, %s diamantes que você recarregou em %s foram renda ilegal e estão congelados.",
    "经审核，来自%s的%s钻石为违规收益，已被冻结" => "Após a revisão, %s diamantes de %s foi renda ilegal e estão congelados.",
    "因触发系统风控，您充值的%s钻石被暂时冻结并限制该充值方式继续充值，请去官网进行身份认证等待系统审核，审核期间您可使用官网其他方式充值，官网：partying.sg" => "Devido ao controle de risco do sistema, %s diamantes que você recarregou foram temporariamente congelados e o método de recarga será impedido de continuar recarregando. Acesse o site oficial para verificação de identidade e aguarde a revisão do sistema. Durante o período de revisão, você pode usar outros métodos para recarregar no site oficial. Site oficial => partying.sg",
    "风险币官方冻结%s钻石通知" => "Aviso de congelamento oficial de %s diamantes de moeda em risco",
    "退回魅力值" => "Valor de encanto devolvido",
    "官方冻结%s钻石通知" => "Aviso de congelamento oficial de %s diamantes ",
    "官方罚款%s钻石通知" => "Aviso de multa oficial de %s diamantes ",
    "官方退还罚款%s钻石" => "O oficial reembolsou %s diamantes de multa",
    "官方赠送金额" => "Valor presenteado pelo oficial",
    "官方赠送魅力值" => "Valor de encanto presenteado pelo oficial",
    "%s钻石提现失败返还至收入余额" => "A retirada de %s diamantes falhou e os mesmos foram devolvidos ao saldo de renda",
    "%s钻石提现失败" => "Falhou de retirar %s diamantes",
    "系统奖励钻石" => "Diamantes recompensados pelo sistema",
    "订单有涉黄行为" => "Existe pornografia no pedido",
    "订单有违规行为" => "Existe comportamento ilegal no pedido",
    "订单有违法行为" => "Existe comportamento ilegal no pedido",
    "大神服务不达标" => "O serviço de Mestre não está à altura do padrão",
    "大神欺诈用户完成订单" => "O Mestre fraudou o usuário para concluir o pedido",
    "被官方没收" => "foi oficialmente confiscado",
    "和" => "e",
    "您%s与【%s】的【%s】订单金额被官方没收" => "O valor dos seus pedidos de %s【%s】com【%s】foi confiscado pelo oficial",
    "，原因：" => ", devido a => ",
    "收到一个红包" => "Recebeu um pacote vermelho",
    "魅力值兑换钻石" => "Trocar valores de encanto por diamentes",
    "您的账号注销申请已通过审核，请在3天内在我->账号设置->账号与安全->账号注销里确认是否注销，3天内未确认则需重新提交注销申请" => "O seu pedido de cancelamento de conta foi analisado, por favor, confirme se deseja cancelar em Meu-Configurações-Conta e Segurança-Excluir a conta em 3 dias. Se você não confirmar dentro de 3 dias, você precisa reenviar o pedido.",
    "由于%s，您的账号注销申请未通过审核" => "Devido a%s, seu pedido de cancelamento de conta não foi aprovado.",
    "你的账号存在风险，已被限制提现。" => "Sua conta está em risco e os saques foram restringidos.",
    "您的账号风险已解除，已恢复提现。" => "O risco da sua conta foi levantado e as retiradas foram retomadas.",
    "0" => "Devido a%s, seu pedido de cancelamento de conta não foi aprovado.",
    "未签约或签约失败" => "Não assinado ou falhou ao assinar",
    "银行卡无效" => "Cartão bancário inválido",
    "签约账号异常" => "Conta assinada anormal",
    "超限额" => "com cota excedida",
    "dana账户有误" => "conta de dana errada",
    "ovo账户有误" => "conta de ovo errada",
    "PLEASE_RATE_THIS_CUSTOMER_SERVICE" => "Por favor, faça uma avaliação ao serviço de atendimento.",
    "YOU_HAVE_TRANSFERRED_THE_MANUAL_SERVICE" => "Olá, está o serviço humano do atendimento para você, descreva seu problema em detalhes por favor.",
    "IF_THERE_ARE_STILL_QUESTIONS" => "Olá, se ainda tiver dúvidas",
    "SUGGEST_YOU_SWITCH_TO_MANUAL_SERVICE" => ", transferir para atendimento ao cliente humano",
    "WHAT_CAN_I_HELP_YOU" => "Oi, em que posso te ajudar？",
    "LONG_TIME_HAVE_NOT_RECEIVED_YOU_REPLY" => "Olá, não recebemos sua resposta há muito tempo e saímos automaticamente do serviço humano.",
    "CURRENT_CUSTOMER_SERVICE_HAVE_NOT_RESPONDED_LONG_TIME" => "Olá, o atendimento atual não respondeu há muito tempo e saímos automaticamente do serviço humano.",
    "SYSTEM_CANNOT_UNDERSTAND_WHAT_YOU_MEAN" => "Olá, o sistema não consegue entender o que você quer dizer",
    "ROBOT_LEVEL_IS_LIMITED" => "Olá, a capacidade do robô é limitada",
    "AutochatTask_720_0" => "Olá, o sistema não consegue entender o que você quer dizer",
    "公会成员%s(ID:%s)申请退会，您还未处理，请尽快处理" => "O membro da guilda %s (ID:%s) solicitou a sair, e você ainda não o processou. Processe-o em breve por favor.",
    "string_user_online" => "chegou online",
    "HI_I_AM" => "Oi, sou",
    "PAYONEER_SUCCESS" => "Sua conta payoneer foi registrada com sucesso!",
    "你的调研报酬已发放，请前往钱包或payoneer账户查看，如有疑问请联系：partying_cs@partying.sg" => "A recompensa à sua pesquisa foi emitida, acesse sua carteira ou conta payoneer para verificar. Se você tiver alguma dúvida, entre em contato com：partying_cs@partying.sg",
    "您的招呼消息已经审核拒绝。您可以进去新人榜看看>>" => "Sua mensagem de cumprimento foi analisada e rejeitada. Você pode ir para a lista de recém-chegados para ver >>",
    "您的招呼消息已经审核通过。您可以进去新人榜看看>>" => "Sua mensagem de cumprimento foi aprovada. Pode ir para a lista de recém-chegados para ver >>",
    "用研任务邮件" => "<html><body><h2>Oi</h2><div><p>Agora tem uma nova tarefa de teste para participar. &lt;%task_name%&gt;#%task_id%, do tipo %task_type%. O teste precisa de ser realizado em %task_plat%, com duração mais ou menos %task_time% mins. Depois de ser concluída e aprovada, você receberá %task_award_num% no valor de %task_thing%. (As recompensas serão emitidas dentro de 3-5 dias úteis) </p><p> Clique no link para começar o teste => <a href=\"%task_user_url%\" target=\"_blank\">%task_url%</a><p> Atenção => O teste será encerrado quando um número suficiente de pessoas concluir o teste, então o link do teste será inválido. Por favor, complete o teste o mais rápido possível. Depois de passar na revisão, a recompensa será enviada para seu email atual, por favor, certifique-se de que este e-mail &lt;survey@thinkerlab.com&gt; já foi adicionado como remetente confiável </em> de </em>. </p><p> se tiver dúvidas, por favor, mande a sua pergunta para thinkerlab_help@thinkerlab.com, e a gente vai dar uma resposta em breve. Tenha um bom teste! </p><br /><p> Equipe de Thinker Lab Se você não deseja mais receber e-mails relevantes enviados por esta plataforma, <a href=\"%unsub_url%\" target=\"_blank\"> Clique aqui para cancelar </a>. (Para não afetar seu pagamento, não cancele a inscrição antes de receber o pagamento) </p></div></body></html>",
    "用研奖励邮件" => "<html><body><h2> Oi </h2><div><p> Parabén ao concluir o teste em &lt;%date%&gt; => &lt;%task_name%&gt; #%task_id% já foi aprovado. Vimos por este meio enviar as recompensas de teste => %task_award_num% em valor de %task_thing%. Obte mais detalhes sobre o uso de cartão do presente </p><p>%task_award_content%<p> em => <a href=\"https://www.amazon.com/gp/help/customer/display.html?nodeId=G5D4TA7NBKQT7GW2\" target=\"_blank\"> Amazon.com.\n Help => Redeem a Gift Card </a></p><p> Se tiver dúvidas, por favor mande a sua pergunta para thinkerlab_help@thinkerlab.com, a gente vai dar uma resposta em breve. </p><p> Tenha um bom teste! </p><br/><p> Equipe de ThinkerLab </p><br/><p> Se você não deseja mais receber e-mails relevantes enviados por esta plataforma, <a href=\"%unsub_url%\" target=\"_blank\"> Clique aqui para cancelar </a>. (Para não afetar seu pagamento, não cancele a inscrição antes de receber o pagamento) </p></div></body></html>",
    "问卷" => "Questionário",
    "访谈" => "Entrevista",
    "可用性测试" => "Teste de usabilidade",
    "电脑" => "Computador",
    "手机" => "Celular",
    "你有新的测试任务" => "Você tem uma nova tarefa de teste",
    "你的测试报酬已到账" => "A recompensa ao seu teste foi recebida na conta.",
    "礼品卡内容" => "Valor do cartão de presente => $%price% &nbsp;&nbsp;&nbsp;&nbsp; Código de recarga => %code% &nbsp;&nbsp;&nbsp;&nbsp; Data de validade => %date%",
    "1美元amazon礼品卡" => "Cartão de presente da Amazon com valor de 1 dólar",
    "充值余额" => "Saldo de recarga",
    "官方冻结%s金币通知" => "Notificação de congelamento oficial de %s moedas",
    "官方罚款%s金币通知" => "Notificação de multa oficial de %s moedas",
    "官方冻结%s金豆通知" => "Notificação de congelamento oficial de %s grãos de ouro",
    "官方罚款%s金豆通知" => "Notificação de multa oficial de %s grãos de ouro",
    "【罚款处罚】该账号由于【%s】，被官方处以罚款%s金币的处罚，系统将会从您的账户余额自动扣取罚金。如对该处罚有异议，可联系客服进行申诉。" => "【Penalidade de Multa】Devido a [%s], a conta foi oficialmente multada em %s moedas e o sistema deduzirá automaticamente a multa do saldo da sua conta. Se você tiver alguma objeção à penalidade, entre em contato com o atendimento ao cliente para recorrer.",
    "【冻结通知】该账号由于【%s】，被官方处以冻结%s金币的处理，系统将会从您账户余额自动执行金额冻结。如对该处罚有异议，可联系客服进行申诉。" => "【Congelamento de Conta】Devido a [%s], a conta está oficialmente sujeita ao congelamento de %s moedas, e o sistema congelará automaticamente o valor do saldo da sua conta. Se você tiver alguma objeção à penalidade, entre em contato com o atendimento ao cliente para recorrer.",
    "【罚款处罚】该账号由于【%s】，被官方处以罚款%s金豆的处罚，系统将会从您的账户余额自动扣取罚金。如对该处罚有异议，可联系客服进行申诉。" => "【Penalidade de Multa】Devido a [%s], a conta foi oficialmente multada em %s grãos de ouro e o sistema deduzirá automaticamente a multa do saldo da sua conta. Se você tiver alguma objeção à penalidade, entre em contato com o atendimento ao cliente para recorrer.",
    "【冻结通知】该账号由于【%s】，被官方处以冻结%s金豆的处理，系统将会从您账户余额自动执行金额冻结。如对该处罚有异议，可联系客服进行申诉。" => "【Congelamento de Conta】Devido a [%s], a conta está oficialmente sujeita ao congelamento de %s grãos de ouro, e o sistema congelará automaticamente o valor do saldo da sua conta. Se você tiver alguma objeção à penalidade, entre em contato com o atendimento ao cliente para recorrer.",
    "官方退还罚款%s金豆" => "O oficial reembolsou %s grãos de ouro de multa",
    "官方退还罚款%s金币" => "O oficial reembolsou %s moedas de multa",
    "【官方赠送金额】官方赠送%s金币，其中填补欠款%s金币，增加%s%s金币，请在我->钱包查收。" => "【Presente Oficial】O oficial doou %s moedas, entre as quais os atrasados ​​de %s moedas são compensadas e %s moedas de %s são adicionadas. Por favor, verifique-as em Meu->Carteira.",
    "【官方赠送金额】官方赠送%s金豆，其中填补欠款%s金豆，增加%s%s金豆，请在我->钱包查收。" => "【Presente Oficial】O oficial doou %s grãos de ouro, entre as quais os atrasados ​​de %s grãos de ouro são compensados e %s grãos de ouro de %s são adicionados. Por favor, verifique-as em Meu->Carteira.",
    "【官方赠送金额】官方赠送%s金币，增加%s%s金币，请在我->钱包查收。" => "【Presente Oficial】O oficial doou %s moedas. Foi adicionado %s modedas de %s. Por favor, verifique-os em Meu->Carteira.",
    "【官方赠送金额】官方赠送%s金豆，增加%s%s金豆，请在我->钱包查收。" => "【Presente Oficial】O oficial doou %s grãos de ouro. Foi adicionado %s grãos de ouro de %s. Por favor, verifique-os em Meu->Carteira.",
    "【官方赠送】官方赠送钻石%s，增加钻石余额%s。" => "【Presente Oficial】O oficial presenteou %s diamantes. O saldo do diamante aumentou %s.",
    "【官方赠送】官方赠送金豆%s，增加金豆余额%s。" => "【Presente Oficial】O oficial presenteou %s grãos de ouro. O saldo do grão de ouro aumentou %s.",
    "官方赠送金豆%s" => "O oficial presentou %s grãos de ouro",
    "ADMINTASK_REASON_1" => "contém palavras sensíveis",
    "ADMINTASK_REASON_2" => "contém conteúdo politicamente sensível",
    "ADMINTASK_REASON_3" => "contém conteúdo abusivo",
    "ADMINTASK_REASON_4" => "Revisão humana",
    "ADMINTASK_REASON_PUSH_SUCCESS" => "Seu avatar foi aprovado",
    "ADMINTASK_REASON_PUSH_FAILE_1" => "Seu avatar não foi aprovado por cause de %reason%",
    "ADMINTASK_REASON_PUSH_FAILE_2" => "Seu avatar não foi aprovado por cause de %reason% e foi limpado.",
    "ADMINTASK_REASON_PUSH_FAILE_3" => "Sua foto de perfil foi excluída por cause de %reason%",
    "ADMINTASK_REASON_PUSH_FAILE_4" => "Seu %fieldValue% %toValue% foi aprovado",
    "ADMINTASK_REASON_PUSH_FAILE_5" => "Seu %fieldValue% %toValue% foi limpado por causa de %reason%",
    "ADMINTASK_REASON_PUSH_FAILE_6" => "%fieldValue% da sua família [%fleetgid%] foi redefinida devido a %reason%",
    "ADMINTASK_REASON_PUSH_FAILE_7" => "%fieldValue% do seu grupo [%group_id%] já foi redefinido por cause de %reason%",
    "ADMINTASK_REASON_PUSH_FAILE_8" => "%fieldValue% da sua sala [%roomrid%] já foi redefinido por cause de %reason%.",
    "ADMINTASK_FIELD_1" => "Nome",
    "ADMINTASK_FIELD_2" => "Assinatura",
    "ADMINTASK_FIELD_3" => "Anônimo",
    "ADMINTASK_FIELD_4" => "Introdução",
    "ADMINTASK_FIELD_5" => "Eu sou o mestre da minha família",
    "ADMINTASK_FIELD_6" => "Eu sou o mestre do meu grupo",
    "ADMINTASK_FIELD_7" => "Anúncios",
    "ADMINTASK_FIELD_8" => "Eu sou o mestre da minha sala",
    "您的联盟房间未通过审核" => "Sua sala de aliança falhou ao ser aprovada",
    "%s魅力值提现失败返还" => "A retirada de %s pontos de encanto falhou e foi reembolsada",
	'在聊天室内说低俗/色情擦边语音' => '在聊天室内说低俗/色情擦边语音',
	'在聊天室内发布低俗/色情擦边图片或视频' => '在聊天室内发布低俗/色情擦边图片或视频',
    '请输入邮箱' => 'por favor insira seu e-mail',
    '检查到多帐号' => 'Várias contas foram detectadas e não podem continuar.',
    '邮箱格式错误' => 'Erro de formato de e-mail',
    '邮箱已经被注册' => 'Desculpe, você já se registrou com este e-mail.',
    '邮箱验证码发送失败' => 'Falha no envio do código de verificação de e-mail. Tente novamente mais tarde',
    '验证码发送太频繁' => 'O código de verificação é enviado com muita frequência. Tente novamente mais tarde',
    '验证码错误' => 'Erro no código de verificação',
    '邮箱不存在' => 'E-mail não existe',
    '请输入姓名' => 'Por favor, digite seu nome',
    '请输入邮件内容' => 'Por favor, preencha o conteúdo do e-mail',
    '参数错误' => 'Erro de parâmetro',
    '性别错误' => 'erro de gênero',
    '生日日期格式错误' => 'erro de formato de data de aniversário',
    '年龄限制18岁' => 'Desculpe, você não atende ao nosso requisito de idade mínima',
    '无效的其他联系方式' => 'Outros detalhes de contato inválidos',
    '无效生日' => 'Insira a data de nascimento correta',
    '无效性别' => 'Digite o sexo correto',
    '无效学历' => 'Insira o nível acadêmico correto',
    '无效国家' => 'Insira o país correto',
    '无效语言' => 'Por favor, digite o idioma correto',
    '无效年收入' => 'Renda anual inválida',
    '请输入地区' => 'Por favor, insira uma região',
    '无效地区' => 'Insira a região correta',
    '请输入手机号码' => 'Por favor, insira o número de telefone',
    '无效的手机号码' => 'número de celular inválido',
    '请输入您PayPal账号的电邮' => 'Por favor, insira o e-mail da sua conta do PayPal',
    '无效的PayPal账号电邮' => 'E-mail da conta do PayPal inválido',
    '注册成功' => 'Sucesso no registro',
    '恭喜您已完成注册' => 'Parabéns pelo registro concluído!',
    '请验证你的邮箱地址' => 'Verifique seu endereço de e-mail.',
    '编号获取失败' => 'Falha ao obter ID',
    '注册邮件' => '<html><body><h2>Verifique seu endereço de e-mail</h2><div><p>Olá,</p><p> Seu código de verificação é:%code%. Esse código é usado apenas para verificar a validade do endereço de e-mail. Para a segurança de sua conta, não o encaminhe para outras pessoas.</p><br /><p>
Equipe ThinkerLab</p></div></body></html>',
    '确认邮件' => '<html><body><h2>Bem-vindo aos respondentes da pesquisa do ThinkerLab!</h2><div><p>Você poderá:</p><p>1. Obter as tarefas de teste mais recentes em tempo real e experimentar diferentes conteúdos de teste.</p><p>2. Compartilhar seus pensamentos e sentimentos reais com desenvolvedores de empresas e produtos.<p>3. Após completar o teste, receber a recompensa correspondente.</p><p>Para garantir que você possa receber normalmente os testes e recompensas mais recentes, adicione este e-mail &lt;survey@thinkerlab.com&gt;como um remetente confiável.</p><br /><p>Equipe ThinkerLab</p><br/><p>Se você não deseja mais receber e-mails relevantes desta plataforma, <a href="%unsub_url%" target="_blank">clique aqui para cancelar a inscrição</a>. (Para não afetar seu pagamento, não cancele a inscrição após concluir o teste e antes de receber o pagamento)</p></div></body></html>',
    '最多可兑换魅力值为' => 'O valor máximo que pode ser trocado por charm é',
    '最多可发送魅力值为' => 'O valor máximo de carisma que pode ser enviado é',
    'app uid已被其他用户占用，请重新输入' => 'O app uid já está ocupado por outro usuário, digite novamente',
    'app uid无效，请重新输入' => 'O uid do aplicativo preenchido é inválido, digite novamente',
    'platform_rules_certified_god_to_cashed_out' => 'De acordo com as regras da plataforma, você só pode desistir após passar na certificação do mestre',
    '你的问题上报已经被收到，你的问题编号为#%s，工程师正在密切关注' => 'O seu feedback do problema foi recebido. O número do assunto é #%s. Os engenheiros estão tratando desse problema.',
    '恭喜获得奖励金额%s星币' => 'Parabéns pela obtenção de moedas de %s estrelas',
    '【冻结通知】该账号由于【%s】，被官方除以冻结%s星币的处理，系统将会从您账户余额自动执行金额冻结，如对该处罚有异议，可联系客服进行申诉' => '[Aviso de congelamento] O número da conta [%s] é dividido pelo congelamento oficial de %s moedas de estrela. O sistema congelará automaticamente o valor do saldo da sua conta. Se você tiver alguma objeção à punição, entre em contato com o serviço de atendimento ao cliente para apelar',
    '【官方冻结扣款提醒】%s 官方冻结%s星币，已扣除%s星币' => '[Lembrete da dedução oficial de congelamento] Em %s, %s moedas de estrelas foram oficialmente congeladas, e %s moedas de estrelas foram deduzidas',
    '资金异常' => 'Fundos anormais',

);

return $__messages;
